"use strict";
function array_p(v){return ((Array["isArray"])(v));};
function tag(a){return a[0];};
var PAIR=["pair"];
var VECTOR=["vector"];
var IMMUTABLE_VECTOR=["immutable-vector"];
var BOX=["box"];
var IMMUTABLE_BOX=["immutable-box"];
var CHAR=["char"];
var MUTABLE_STRING=["mutable-string"];
var BYTES=["bytes"];
var MUTABLE_BYTES=["mutable-bytes"];
var SYMBOL=["symbol"];
var KEYWORD=["keyword"];
var VALUES=["values"];
var STRUCT_TYPE_DESCRIPTOR=["struct-type-descriptor"];
var STRUCT=["struct"];
var NAMESPACE=["namespace"];
var STRING_PORT=["string-port"];
var EOF_OBJECT=["eof-object"];
var CONTINUATION_MARK_SET=["continuation-mark-set"];
var PARAMETERIZATION=["parameterization"];
var CLOS="CLOS";
var PARAMETER=["parameter"];
var VOID=[];
var NULL=[];
var parameterization_key=["parameterization-key"];
var TOP_CMS=((function(ht){(ht[parameterization_key]=[PARAMETERIZATION,[[],false]]);return [ht,false];})([]));
var CMS=TOP_CMS;
function dispatch_case_lambda(){var args=arguments,n=(args.length-1),caseclos=args[0];var arities=caseclos[2],closures=caseclos[3],a=0,j=false,clos=false,lab=false;(j=((function(b){{var i=0,t=(n+1),cont=true;while((true&&cont&&(i<t))){((function(i_1){skip:while(true){(a=arities[i_1]);(b=(b||((((n===a)||((a<0)&&(n>=((-a)-1))))===false)?false:i_1)));if(!(b===false)){(cont=false);break skip;}else ;;(i+=1);break skip;};;return undefined;})(i));};undefined;}return b;})(false)));(clos=closures[j]);(lab=clos[1]);return ((function(t){return (((false||(t===0))===false)?(((false||(t===1))===false)?(((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?((function(){args[0]=clos;return ((lab.apply)(false,args));})()):((function(){return (lab(clos,args[1],args[2],args[3],args[4]));})())):((function(){return (lab(clos,args[1],args[2],args[3]));})())):((function(){return (lab(clos,args[1],args[2]));})())):((function(){return (lab(clos,args[1]));})())):((function(){return (lab(clos));})()));})(n));};
function PRIM_a(a,b){var n=arguments.length,args=arguments,s;return ((function(t){return (((false||(t===2))===false)?(((false||(t===1))===false)?(((false||(t===0))===false)?((function(){(s=(a+b));{var i=2,t_2=n;while((true&&true&&(i<t_2))){((function(i_3){(s=(s+args[i_3]));return (i+=1);})(i));};undefined;}return s;})()):((function(){return 0;})())):((function(){return a;})())):((function(){return (a+b);})()));})(arguments.length));};
function PRIM_(a,b){var n=arguments.length,args=arguments,s;return ((function(t){return (((false||(t===2))===false)?(((false||(t===1))===false)?(((false||(t===0))===false)?((function(){(s=(a-b));{var i=2,t_4=n;while((true&&true&&(i<t_4))){((function(i_5){(s=(s-args[i_5]));return (i+=1);})(i));};undefined;}return s;})()):((function(){return 0;})())):((function(){return (-a);})())):((function(){return (a-b);})()));})(arguments.length));};
function PRIM_m(a,b){var n=arguments.length,args=arguments,s;return ((function(t){return (((false||(t===2))===false)?(((false||(t===1))===false)?(((false||(t===0))===false)?((function(){(s=(a*b));{var i=2,t_6=n;while((true&&true&&(i<t_6))){((function(i_7){(s=(s*args[i_7]));return (i+=1);})(i));};undefined;}return s;})()):((function(){return 1;})())):((function(){return a;})())):((function(){return (a*b);})()));})(arguments.length));};
function PRIM_q(a,b){var n=arguments.length,args=arguments,s;return ((function(t){return (((false||(t===2))===false)?(((false||(t===1))===false)?(((false||(t===0))===false)?((function(){(s=(a/b));{var i=2,t_8=n;while((true&&true&&(i<t_8))){((function(i_9){(s=(s/args[i_9]));return (i+=1);})(i));};undefined;}return s;})()):((function(){return (error("PRIM/ expects at least one argument"));})())):((function(){return (1/a);})())):((function(){return (a/b);})()));})(arguments.length));};
function PRIM_eq(a,b){var n=arguments.length,args=arguments,s,r;return ((function(t){return (((false||(t===2))===false)?(((false||(t===0)||(t===1))===false)?((function(){(s=(a===b));{var i=2,t_10=n;while((true&&true&&(i<t_10))){((function(i_11){(s=(s&&(a===args[i_11])));return (i+=1);})(i));};undefined;}return s;})()):((function(){return (error("PRIM= expects at least two arguments"));})())):((function(){return (a===b);})()));})(arguments.length));};
function PRIM_l_eq(a,b){var n=arguments.length,args=arguments,s,r;return ((function(t){return (((false||(t===2))===false)?(((false||(t===0)||(t===1))===false)?((function(){(s=(a<=b));{var i=2,t_12=(n-1);while((true&&true&&(i<t_12))){((function(i_13){(s=(s&&(args[i_13]<=args[(i_13+1)])));return (i+=1);})(i));};undefined;}return s;})()):((function(){return (error("PRIM<= expects at least two arguments"));})())):((function(){return (a<=b);})()));})(arguments.length));};
function PRIM_g_eq(a,b){var n=arguments.length,args=arguments,s,r;return ((function(t){return (((false||(t===2))===false)?(((false||(t===0)||(t===1))===false)?((function(){(s=(a>=b));{var i=2,t_14=(n-1);while((true&&true&&(i<t_14))){((function(i_15){(s=(s&&(args[i_15]>=args[(i_15+1)])));return (i+=1);})(i));};undefined;}return s;})()):((function(){return (error("PRIM>= expects at least two arguments"));})())):((function(){return (a>=b);})()));})(arguments.length));};
function PRIM_g(a,b){var n=arguments.length,args=arguments,s,r;return ((function(t){return (((false||(t===2))===false)?(((false||(t===0)||(t===1))===false)?((function(){(s=(a>b));{var i=2,t_16=(n-1);while((true&&true&&(i<t_16))){((function(i_17){(s=(s&&(args[i_17]>args[(i_17+1)])));return (i+=1);})(i));};undefined;}return s;})()):((function(){return (error("PRIM> expects at least two arguments"));})())):((function(){return (a>b);})()));})(arguments.length));};
function PRIM_l(a,b){var n=arguments.length,args=arguments,s,r;return ((function(t){return (((false||(t===2))===false)?(((false||(t===0)||(t===1))===false)?((function(){(s=(a<b));{var i=2,t_18=(n-1);while((true&&true&&(i<t_18))){((function(i_19){(s=(s&&(args[i_19]<args[(i_19+1)])));return (i+=1);})(i));};undefined;}return s;})()):((function(){return (error("PRIM< expects at least two arguments"));})())):((function(){return (a<b);})()));})(arguments.length));};
function boolean_p(v){return ((typeof(v))==="boolean");};
function PRIM_not(x){return ((x===false)?true:false);};
function equal_p(v,w){return ((((boolean_p(v))&&(boolean_p(w)))===false)?((((number_p(v))&&(number_p(w)))===false)?((((symbol_p(v))&&(symbol_p(w)))===false)?((((null_p(v))&&(null_p(w)))===false)?((((pair_p(v))&&(pair_p(w)))===false)?((((void_p(v))&&(void_p(w)))===false)?((((char_p(v))&&(char_p(w)))===false)?((((immutable_string_p(v))&&(immutable_string_p(w)))===false)?((((mutable_string_p(v))&&(mutable_string_p(w)))===false)?((((vector_p(v))&&(vector_p(w)))===false)?((((box_p(v))&&(box_p(w)))===false)?((((bytes_p(v))&&(bytes_p(w)))===false)?((((keyword_p(v))&&(keyword_p(w)))===false)?((true===false)?undefined:((function(){return false;})())):((function(){return (keyword_eq_p(v,w));})())):((function(){return (bytes_eq_p(v,w));})())):((function(){return (equal_p((unbox(v)),(unbox(w))));})())):((function(){return ((function(b){{var xs=v,n=(vector_length(xs)),i=0,xs_22=w,n_20=(vector_length(xs_22)),i_21=0,cont=true;while((true&&cont&&(i<n)&&(i_21<n_20))){((function(x,y){skip:while(true){(b=(b&&(equal_p(x,y))));if(!((!b)===false)){(cont=false);break skip;}else ;;(i+=1);(i_21+=1);break skip;};;return undefined;})(xs[(i+1)],xs_22[(i_21+1)]));};undefined;}return b;})(true));})())):((function(){return (string_eq_p(v,w));})())):((function(){return (v===w);})())):((function(){return (char_eq_p(v,w));})())):((function(){return true;})())):((function(){return ((equal_p((unsafe_car(v)),(unsafe_car(w))))&&(equal_p((unsafe_cdr(v)),(unsafe_cdr(w)))));})())):((function(){return true;})())):((function(){return (symbol_eq_p(v,w));})())):((function(){return (v===w);})())):((function(){return (v===w);})()));};
function eqv_p(v,w){return ((((number_p(v))&&(number_p(w)))===false)?((((char_p(v))&&(char_p(w)))===false)?((true===false)?undefined:((function(){return (v===w);})())):((function(){return ((char__ginteger(v))===(char__ginteger(w)));})())):((function(){return (v===w);})()));};
function eq_p(v1,v2){return (v1===v2);};
function immutable_p(v){return ((immutable_string_p(v))||(immutable_bytes_p(v))||(immutable_vector_p(v))||(immutable_box_p(v)));};
function number_p(v){return ((typeof(v))==="number");};
function complex_p(v){return (number_p(v));};
function real_p(v){return (number_p(v));};
function rational_p(v){return ((number_p(v))&&((Number["isFinite"])(v)));};
function integer_p(v){return ((Number["isInteger"])(v));};
function exact_integer_p(v){return (((typeof(v))==="number")&&(v===(+v))&&(v===(v|0)));};
function exact_nonnegative_integer_p(v){return ((exact_integer_p(v))&&(v>=0));};
function exact_positive_integer_p(v){return ((exact_integer_p(v))&&(v>0));};
function inexact_real_p(v){return ((real_p(v))&&(inexact_p(v)));};
function fixnum_p(v){return (exact_integer_p(v));};
function flonum_p(v){return ((number_p(v))&&(!(exact_integer_p(v))));};
function double_flonum_p(v){return (flonum_p(v));};
function single_flonum_p(v){return (flonum_p(v));};
function zero_p(z){return (z===0);};
function positive_p(x){return (x>0);};
function negative_p(x){return (x<0);};
function even_p(n){return (0===(n%2));};
function odd_p(n){return (1===(n%2));};
function exact_p(z){return (exact_integer_p(z));};
function inexact_p(z){return ((number_p(z))&&(!(exact_p(z))));};
function inexact__gexact(z){return z;};
function exact__ginexact(z){return z;};
function real__gsingle_flonum(x){return x;};
function real__gdouble_flonum(x){return x;};
function $_a(z1,z2){var n=arguments.length,res;if(!((n===2)===false))(res=(z1+z2));else if(!((n===1)===false))(res=z1);else if(!((n===0)===false))(res=0);else {var sum=(z1+z2),i=2,args=arguments;while((i<n)){(sum+=args[i]);(i+=1);};(res=sum);};;;return res;};
function $_(z1,z2){var n=arguments.length,res;if(!((n===2)===false))(res=(z1-z2));else if(!((n===1)===false))(res=(-z1));else {var sum=(z1-z2),i=2,args=arguments;while((i<n)){(sum-=args[i]);(i+=1);};(res=sum);};;return res;};
function $_m(z1,z2){var n=arguments.length,res;if(!((n===2)===false))(res=(z1*z2));else if(!((n===1)===false))(res=z1);else if(!((n===0)===false))(res=1);else {var prod=(z1*z2),i=2,args=arguments;while((i<n)){(prod*=args[i]);(i+=1);};(res=prod);};;;return res;};
function $_q(z1,z2){var n=arguments.length,res;if(!((n===2)===false))(res=(z1/z2));else if(!((n===1)===false))(res=(1/z1));else {var quot=(z1/z2),i=2,args=arguments;while((i<n)){(quot/=args[i]);(i+=1);};(res=quot);};;return res;};
function quotient(n,m){return ((Math.floor)((n/m)));};
function remainder(n,m){return (n%m);};
function quotient_qremainder(n,m){return (values((quotient(n,m)),(remainder(n,m))));};
function modulo(n,m){return (((n%m)+m)%m);};
function add1(z){return (z+1);};
function sub1(z){return (z-1);};
function abs(x){return ((Math.abs)(x));};
function max(){return ((Math.max.apply)(false,arguments));};
function min(){return ((Math.min.apply)(false,arguments));};
function gcd(n,m){var args=arguments,i,g,l;return ((function(t){return (((false||(t===2))===false)?(((false||(t===1))===false)?(((false||(t===0))===false)?((function(){(l=args.length);(g=args[0]);{var i_24=1,t_23=l;while((true&&true&&(i_24<t_23))){((function(i_25){(g=(gcd(g,args[i_25])));return (i_24+=1);})(i_24));};undefined;}return g;})()):((function(){return 0;})())):((function(){return n;})())):((function(){return (gcd2(n,m));})()));})(arguments.length));};
function gcd2(n,m){var a,b;if(!((n<0)===false)){(n=(-n));}else ;;if(!((m<0)===false)){(m=(-m));}else ;;(a=(((n>m)===false)?m:n));(b=(((n<m)===false)?m:n));var res=false;while((!res)){(((b===0)===false)?((true===false)?undefined:((function(){(a%=b);return (((a===0)===false)?((true===false)?undefined:((function(){return (b%=a);})())):((function(){return (res=b);})()));})())):((function(){return (res=a);})()));};return res;};
function round(x){var r=((Math.round)(x));return (((((((x>0)===false)?(-x):x)%1)===0.5)===false)?r:(((even_p(r))===false)?(r-1):r));};
function floor(x){return ((Math.floor)(x));};
function ceiling(x){return ((Math.ceil)(x));};
function truncate(x){return ((Math.trunc)(x));};
function sqrt(x){return ((Math.sqrt)(x));};
function integer_sqrt(n){return ((Math.floor)(((Math.sqrt)(n))));};
function integer_sqrt_qremainder(n){var s=((Math.floor)(((Math.sqrt)(n))));return (values(s,(n-(s*s))));};
function expt(z,w){return ((Math.pow)(z,w));};
function exp(z){return ((Math.exp)(z));};
function log(z){return ((Math.log)(z));};
function sin(z){return ((Math.sin)(z));};
function cos(z){return ((Math.sin)(z));};
function tan(z){return ((Math.tan)(z));};
function asin(z){return ((Math.asin)(z));};
function acos(z){return ((Math.acos)(z));};
function atan(y,x){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?((function(){return "error: atan - todo - raise exception";})()):((function(){return ((Math.atan)(y,x));})())):((function(){return ((Math.atan)(y));})()));})(arguments.length));};
function real_part(z){return z;};
function image_part(z){return 0;};
function magnitude(z){return ((Math.abs)(z));};
function angle(z){return (((z>0)===false)?(((z<0)===false)?((true===false)?undefined:((function(){return (error("angle","undefined for 0"));})())):((function(){return Math["PI"];})())):((function(){return 0;})()));};
function random(k,rand_gen){return ((Math.floor)((((Math.random)())*k)));};
function random_seed(k){return (Void());};
function make_pseudo_random_generator(){return false;};
function pseudo_random_generator_p(v){return (eq_p(v,false));};
function current_pseudo_random_generator(rand_gen){return false;};
function pseudo_random_generator__gvector(rand_gen){return (vector());};
function vector__gpseudo_random_generator(vec){return false;};
function vector__gpseudo_random_generator_e(rand_gen,vec){return (Void());};
function pseudo_random_generator_vector_p(v){return (vector_p(v));};
function number__gstring(z,radix){var num=(Number(z));return ((num["toString"])(radix));};
function string__gnumber(s,radix){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?((function(){return (error("string->number","expected one or two arguments"));})()):((function(){return (parseFloat(s,radix));})())):((function(){return (parseFloat(s));})()));})(arguments.length));};
var pi=Math["PI"];
function nan_p(x){return (x===NaN);};
function infinite_p(x){return ((x===Infinity)||(x===(-Infinity)));};
function string_p(v){return (((typeof(v))==="string")||((array_p(v))&&((tag(v))===MUTABLE_STRING)));};
function immutable_string_p(v){return ((typeof(v))==="string");};
function mutable_string_p(v){return ((array_p(v))&&((tag(v))===MUTABLE_STRING));};
function make_string(k,ch){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?((function(){return (error("make-string","expected at one or two argument"));})()):((function(){return (make_string2(k,ch));})())):((function(){return (make_string1(k));})()));})(arguments.length));};
function make_string1(k){return (make_string2(k," "));};
function make_string2(k,ch){var a=(Array((k+1)));(a[0]=MUTABLE_STRING);{var i=1,t=(k+1);while((true&&true&&(i<t))){((function(i_26){(a[i_26]=ch[1]);return (i+=1);})(i));};undefined;}return a;};
function make_primitive_string(n,c){var s="";while(true){if(!((!((n&1)===0))===false)){(s+=c);}else ;;(n>>=1);if(!((n===0)===false))break;else (c+=c);;};return s;};
function string__gimmutable_string(s){return ((((typeof(s))==="string")===false)?((true===false)?undefined:((function(){var n_a1=s.length,n=(n_a1-1),a=(Array(n));{var i=0,t=n;while((true&&true&&(i<t))){((function(i_27){(a[i_27]=s[(i_27+1)]);return (i+=1);})(i));};undefined;}return (String(((a.join)(""))));})())):((function(){return s;})()));};
function immutable_string__gstring(str_28){var n=str_28.length,a=(Array((n+1)));(a[0]=MUTABLE_STRING);{var i=0,t=n;while((true&&true&&(i<t))){((function(i_29){(a[(i_29+1)]=str_28[i_29]);return (i+=1);})(i));};undefined;}return a;};
function string(){var args=arguments,n=args.length;var a=(Array((n+1)));(a[0]=MUTABLE_STRING);{var i=0,t=n;while((true&&true&&(i<t))){((function(i_30){(a[(i_30+1)]=args[i_30][1]);return (i+=1);})(i));};undefined;}return a;};
function string_length(s){return ((((typeof(s))==="string")===false)?(s.length-1):s.length);};
function string_ref(s,i){return ((((typeof(s))==="string")===false)?[CHAR,s[(i+1)]]:[CHAR,s[i]]);};
function string_set_e(s,i,c){return (s[(i+1)]=c[1]);};
function substring3(str_31,start,end){return ((str_31.substring)(start,end));};
function substring2(str_32,start){return ((str_32.substring)(start,(string_length(str_32))));};
function substring(){var args=arguments;return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?((function(){return (error("substring","expected two to three arguments"));})()):((function(){return (substring3(args[0],args[1],args[2]));})())):((function(){return (substring2(args[0],args[1]));})()));})(arguments.length));};
function string_eq_p(str1,str2){return (((immutable_string_p(str1))===false)?(((immutable_string_p(str2))===false)?((string__gimmutable_string(str1))===(string__gimmutable_string(str2))):((string__gimmutable_string(str1))===str2)):(((immutable_string_p(str2))===false)?(str1===(string__gimmutable_string(str2))):(str1===str2)));};
function string_l_p(str1,str2){return (((immutable_string_p(str1))===false)?(((immutable_string_p(str2))===false)?((string__gimmutable_string(str1))<(string__gimmutable_string(str2))):((string__gimmutable_string(str1))<str2)):(((immutable_string_p(str2))===false)?(str1<(string__gimmutable_string(str2))):(str1<str2)));};
function string_g_p(str1,str2){return (((immutable_string_p(str1))===false)?(((immutable_string_p(str2))===false)?((string__gimmutable_string(str1))>(string__gimmutable_string(str2))):((string__gimmutable_string(str1))>str2)):(((immutable_string_p(str2))===false)?(str1>(string__gimmutable_string(str2))):(str1>str2)));};
function string_l_eq_p(str1,str2){return (((immutable_string_p(str1))===false)?(((immutable_string_p(str2))===false)?((string__gimmutable_string(str1))<=(string__gimmutable_string(str2))):((string__gimmutable_string(str1))<=str2)):(((immutable_string_p(str2))===false)?(str1<=(string__gimmutable_string(str2))):(str1<=str2)));};
function string_g_eq_p(str1,str2){return (((immutable_string_p(str1))===false)?(((immutable_string_p(str2))===false)?((string__gimmutable_string(str1))>=(string__gimmutable_string(str2))):((string__gimmutable_string(str1))>=str2)):(((immutable_string_p(str2))===false)?(str1>=(string__gimmutable_string(str2))):(str1>=str2)));};
function string_upcase(str_33){return (((immutable_string_p(str_33))===false)?(string_upcase((string__gimmutable_string(str_33)))):(immutable_string__gstring((String(((str_33["toUpperCase"])()))))));};
function string_downcase(str_34){return (((immutable_string_p(str_34))===false)?(string_downcase((string__gimmutable_string(str_34)))):(immutable_string__gstring((String(((str_34["toLowerCase"])()))))));};
function string__glist(s){return ((function(xs){{var s_35=s,n=s_35.length,i=0;while((true&&true&&(i<n))){((function(c){(xs=(cons(c,xs)));return (i+=1);})((string_ref(s_35,i))));};undefined;}return (reverse(xs));})(NULL));};
function string_append2(str1,str2){return ((str1.concat)(str2));};
function string_append(){var args=arguments;var as2=((function(){var n=args.length,a=[n],i=0;{var a_37=args,n_36=a_37.length,i_38=0;while((true&&true&&(i_38<n_36))){((function(a_40){(a[i]=a_40);(i+=1);return (i_38+=1);})(a_37[i_38]));};undefined;}if(!((i<n)===false)){var i_39=i,t=n;while((true&&true&&(i_39<t))){((function(j){a[j]=0;return (i_39+=1);})(i_39));};undefined;}else ;;return a;})());return ((as2.join)(""));};
function bytes_p(v){return ((array_p(v))&&(((tag(v))===BYTES)||((tag(v))===MUTABLE_BYTES)));};
function immutable_bytes_p(v){return ((array_p(v))&&((tag(v))===BYTES));};
function mutable_bytes_p(v){return ((array_p(v))&&((tag(v))===MUTABLE_BYTES));};
function bytes__gInt8Array(bs){return bs[1];};
function make_bytes(k,b){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?((function(){return (error("make-bytes","expected one or two arguments"));})()):((function(){return (make_bytes2(k,b));})())):((function(){return (make_bytes1(k));})()));})(arguments.length));};
function make_bytes1(k){var is=new Int8Array(k);return [MUTABLE_BYTES,is];};
function make_bytes2(k,b){var bs=new Int8Array(k);{var i=0,t=k;while((true&&true&&(i<t))){((function(i_41){(bs[i_41]=b);return (i+=1);})(i));};undefined;}return [MUTABLE_BYTES,bs];};
function bytes(){var args=arguments,n=args.length,is=(Int8Array(n));((is.set)(args));return [MUTABLE_BYTES,is];};
function bytes__gimmutable_bytes(bs){return [BYTES,((Int8Array.from)(bs[1]))];};
function immutable_bytes__gbytes(bs){return [MUTABLE_BYTES,((Int8Array.from)(bs[1]))];};
function byte_p(v){return ((exact_integer_p(v))&&(0<=v<=255));};
function bytes_length(bs){((console.log)("bytes-length:"));((console.log)(bs[1]));return bs[1]["length"];};
function bytes_ref(bs,k){return bs[1][k];};
function bytes_set_e(bs,k,b){var is=bs[1];return (is[k]=b);};
function subbytes(bs,start,end){return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?((function(){return (error("subbytes","expected two or three arguments"));})()):((function(){return (subbytes3(bs,start,end));})())):((function(){return (subbytes2(bs,start));})()));})(arguments.length));};
function subbytes2(bs,start){var is=bs[1],end=is["length"],k=(end-start),t=new Int8Array(k);{var i=start,t_42=end;while((true&&true&&(i<t_42))){((function(i_43){(t[i_43]=is[i_43]);return (i+=1);})(i));};undefined;}return [MUTABLE_BYTES,is];};
function subbytes3(bs,start,end){var is=bs[1],k=(end-start),t=new Int8Array(k);{var i=start,t_44=end;while((true&&true&&(i<t_44))){((function(i_45){(t[i_45]=is[i_45]);return (i+=1);})(i));};undefined;}return [MUTABLE_BYTES,is];};
function bytes_copy(bs){return (subbytes2(bs,0));};
function bytes_eq_p(bs1,bs2){var n1=(bytes_length(bs1)),n2=(bytes_length(bs2)),is1=bs1[1],is2=bs2[1];return ((n1===n2)&&((function(b){{var i=0,t=n1,cont=true;while((true&&cont&&(i<t))){((function(i_46){skip:while(true){(b=(b&&(is1[i_46]===is2[i_46])));if(!((!b)===false)){(cont=false);break skip;}else ;;(i+=1);break skip;};;return undefined;})(i));};undefined;}return b;})(true)));};
function char_p(v){return ((array_p(v))&&((tag(v))===CHAR));};
function make_char(prim_js_str){return [CHAR,prim_js_str];};
function char__ginteger(c){var s=c[1];return ((s["charCodeAt"])(0));};
function integer__gchar(i){return (String(((String["fromCharCode"])(i))));};
function char_eq_p(c1,c2){return (c1[1]===c2[1]);};
function symbol_p(v){return ((array_p(v))&&((tag(v))===SYMBOL));};
function symbol_interned_p(sym){return ((typeof(sym[1]))==="string");};
function symbol_eq_p(sym1,sym2){return (((symbol_interned_p(sym1))&&(symbol_interned_p(sym2))&&(sym1[1]===sym2[1]))||(sym1===sym2));};
function symbol__gstring(sym){var js_str=sym[1],n=js_str.length,a=(Array((n+1)));(a[0]=MUTABLE_STRING);{var i=0,t=n;while((true&&true&&(i<t))){((function(i_47){(a[(i_47+1)]=js_str[i_47]);return (i+=1);})(i));};undefined;}return a;};
function symbol__gimmutable_string(sym){return (String(sym[1]));};
var symbol_table=[];
function string__gsymbol(str_48){var t=(typeof(str_48)),r,old;(old=symbol_table[str_48]);if(!((symbol_p(old))===false))((function(){return (r=old);})());else if(!((t==="string")===false))((function(){(r=[SYMBOL,str_48]);return (symbol_table[str_48]=r);})());else if(!((t==="object")===false))((function(){var n_a1=t.length,n=(n_a1-1),a=(Array(n));{var i=0,t_49=n;while((true&&true&&(i<t_49))){((function(i_50){(a[i_50]=str_48[(i_50+1)]);return (i+=1);})(i));};undefined;}(r=[SYMBOL,(String(((a.join)(""))))]);return (symbol_table[str_48]=r);})());else if(!(true===false))((function(){return (error("string->symbol","expected a string"));})());else undefined;;;;;return r;};
function string__guninterned_symbol(str_51){return [SYMBOL,new String(str_51)];};
var gensym_counter=0;
function gensym(base){return ((function(t){return (((false||(t===0))===false)?(((false||(t===1))===false)?((function(){return (error("gensym","expected at most one argument"));})()):((function(){return (gensym1(base));})())):((function(){return (gensym0());})()));})(arguments.length));};
function gensym0(){(gensym_counter+=1);return [SYMBOL,new String(("g"+gensym_counter))];};
function gensym1(base){((console.log)(("gensym1: "+base)));(gensym_counter+=1);return [SYMBOL,new String((base+gensym_counter))];};
function symbol_l_p(a_sym,b_sym){return (string_l_p((symbol__gstring(a_sym)),(symbol__gstring(b_sym))));};
function error(who,msg){return ((console.log)(("error: "+who+": "+msg)));};
function keyword_p(v){return ((array_p(v))&&((tag(v))===KEYWORD));};
function keyword__gstring(key){return (immutable_string__gstring(key[1]));};
function string__gkeyword(str_52){var istr=(string__gimmutable_string(str_52));return [KEYWORD,istr];};
function keyword_l_p(key1,key2){return (key1[1]<key1[2]);};
function keyword_eq_p(key1,key2){return (key1[1]===key2[1]);};
function pair_p(v){return ((array_p(v))&&((tag(v))===PAIR));};
function null_p(v){return (v===NULL);};
function cons(a,d){return [PAIR,(list_p(d)),a,d];};
function unsafe_car(p){return p[2];};
var car=unsafe_car;
function unsafe_cdr(p){return p[3];};
var cdr=unsafe_cdr;
function cddr(v){return (cdr((cdr(v))));};
var Null=NULL;
function list_p(v){return ((v===NULL)||((array_p(v))&&((tag(v))===PAIR)&&v[1]));};
function list(){var args=arguments,n=args.length,n_1=(n-1),xs=NULL;{var i=0,t=n;while((true&&true&&(i<t))){((function(i_53){(xs=(cons(args[(n_1-i_53)],xs)));return (i+=1);})(i));};undefined;}return xs;};
function list_m(){var args=arguments,n=args.length;return (((n===0)===false)?((true===false)?undefined:((function(){var n_2=(n-2),xs=args[(n_2+1)];{var i=0,t=(n-1);while((true&&true&&(i<t))){((function(i_54){(xs=(cons(args[(n_2-i_54)],xs)));return (i+=1);})(i));};undefined;}return xs;})())):((function(){return (error("list*","expected one or more arguments"));})()));};
function build_list(n,proc){var a=(Array(n));{var i=0,t=n;while((true&&true&&(i<t))){((function(i_55){(a[i_55]=((proc[1])(proc,i_55)));return (i+=1);})(i));};undefined;}return (array__glist(a));};
function length(xs){var n=0;while((pair_p(xs))){(n+=1);(xs=(cdr(xs)));};return n;};
function list_ref(xs,i){var ret;if(!((i===0)===false))((function(){return (ret=(car(xs)));})());else if(!((i===1)===false))((function(){return (ret=(car((cdr(xs)))));})());else if(!(true===false))((function(){{var i_56=0,t=(i-1);while((true&&true&&(i_56<t))){((function(j){(xs=(cdr(xs)));return (i_56+=1);})(i_56));};undefined;}return (ret=(car(xs)));})());else undefined;;;;return ret;};
function list_tail(xs,pos){while((!(pos===0))){(xs=(cdr(xs)));(pos-=1);};return xs;};
function append(){var args=arguments,n=args.length;return ((function(t){return (((false||(t===0))===false)?(((false||(t===1))===false)?(((false||(t===2))===false)?((function(){var ret=args[(n-1)],i=(n-2);while((i>=0)){(ret=(append2(args[i],ret)));(i-=1);};return ret;})()):((function(){return (append2(args[0],args[1]));})())):((function(){return args[0];})())):((function(){return NULL;})()));})(n));};
function append2(xs,ys){var ret=ys;if(!((!(null_p(xs)))===false)){var axs=(list__garray(xs)),n=axs.length,n_1=(n-1);{var i=0,t=n;while((true&&true&&(i<t))){((function(i_57){(ret=(cons(axs[(n_1-i_57)],ret)));return (i+=1);})(i));};undefined;}}else ;;return ret;};
function reverse(xs){var result=NULL;while((!(null_p(xs)))){(result=(cons((car(xs)),result)));(xs=(cdr(xs)));};return result;};
var alt_reverse=reverse;
function map(proc,xs,ys,zs){return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?(((false||(t===0))===false)?((function(){return (1/0);})()):((function(){return (error("map","expected at least two arguments"));})())):((function(){return (((js_function_p(proc))===false)?(((closure_p(proc))===false)?((true===false)?undefined:((function(){return (("ERROR - map")());})())):((function(){var lab=proc[1];return ((function(xs_72){{var xs_73=xs,xs_74=ys,xs_75=zs;while((true&&true&&(!(null_p(xs_73)))&&(!(null_p(xs_74)))&&(!(null_p(xs_75))))){((function(x,y,z){(xs_72=(cons((lab(proc,false,x,y,z)),xs_72)));(xs_73=(cdr(xs_73)));(xs_74=(cdr(xs_74)));return (xs_75=(cdr(xs_75)));})((car(xs_73)),(car(xs_74)),(car(xs_75))));};undefined;}return (reverse(xs_72));})(NULL));})())):((function(){return ((function(xs_68){{var xs_69=xs,xs_70=ys,xs_71=zs;while((true&&true&&(!(null_p(xs_69)))&&(!(null_p(xs_70)))&&(!(null_p(xs_71))))){((function(x,y,z){(xs_68=(cons((proc(x,y,z)),xs_68)));(xs_69=(cdr(xs_69)));(xs_70=(cdr(xs_70)));return (xs_71=(cdr(xs_71)));})((car(xs_69)),(car(xs_70)),(car(xs_71))));};undefined;}return (reverse(xs_68));})(NULL));})()));})())):((function(){return (((js_function_p(proc))===false)?(((closure_p(proc))===false)?((true===false)?undefined:((function(){return (("ERROR - map")());})())):((function(){var lab=proc[1];return ((function(xs_65){{var xs_66=xs,xs_67=ys;while((true&&true&&(!(null_p(xs_66)))&&(!(null_p(xs_67))))){((function(x,y){(xs_65=(cons((lab(proc,false,x,y)),xs_65)));(xs_66=(cdr(xs_66)));return (xs_67=(cdr(xs_67)));})((car(xs_66)),(car(xs_67))));};undefined;}return (reverse(xs_65));})(NULL));})())):((function(){return ((function(xs_62){{var xs_63=xs,xs_64=ys;while((true&&true&&(!(null_p(xs_63)))&&(!(null_p(xs_64))))){((function(x,y){(xs_62=(cons((proc(x,y)),xs_62)));(xs_63=(cdr(xs_63)));return (xs_64=(cdr(xs_64)));})((car(xs_63)),(car(xs_64))));};undefined;}return (reverse(xs_62));})(NULL));})()));})())):((function(){return (((js_function_p(proc))===false)?(((closure_p(proc))===false)?((true===false)?undefined:((function(){return (("ERROR - map")());})())):((function(){var lab=proc[1];return ((function(xs_60){{var xs_61=xs;while((true&&true&&(!(null_p(xs_61))))){((function(x){(xs_60=(cons((lab(proc,false,x)),xs_60)));return (xs_61=(cdr(xs_61)));})((car(xs_61))));};undefined;}return (reverse(xs_60));})(NULL));})())):((function(){return ((function(xs_58){{var xs_59=xs;while((true&&true&&(!(null_p(xs_59))))){((function(x){(xs_58=(cons((proc(x)),xs_58)));return (xs_59=(cdr(xs_59)));})((car(xs_59))));};undefined;}return (reverse(xs_58));})(NULL));})()));})()));})(arguments.length));};
function andmap(proc,xs,ys,zs){return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?(((false||(t===0))===false)?((function(){return (1/0);})()):((function(){return (error("andmap","expected at least two arguments"));})())):((function(){return ((function(b){{var xs_79=xs,xs_80=ys,xs_81=zs,cont=true;while((true&&cont&&(!(null_p(xs_79)))&&(!(null_p(xs_80)))&&(!(null_p(xs_81))))){((function(x,y,z){skip:while(true){(b=(b&&((proc.call)(false,x,y,z))));if(!((!b)===false)){(cont=false);break skip;}else ;;(xs_79=(cdr(xs_79)));(xs_80=(cdr(xs_80)));(xs_81=(cdr(xs_81)));break skip;};;return undefined;})((car(xs_79)),(car(xs_80)),(car(xs_81))));};undefined;}return b;})(true));})())):((function(){return ((function(b){{var xs_77=xs,xs_78=ys,cont=true;while((true&&cont&&(!(null_p(xs_77)))&&(!(null_p(xs_78))))){((function(x,y){skip:while(true){(b=(b&&((proc.call)(false,x,y))));if(!((!b)===false)){(cont=false);break skip;}else ;;(xs_77=(cdr(xs_77)));(xs_78=(cdr(xs_78)));break skip;};;return undefined;})((car(xs_77)),(car(xs_78))));};undefined;}return b;})(true));})())):((function(){return ((function(b){{var xs_76=xs,cont=true;while((true&&cont&&(!(null_p(xs_76))))){((function(x){skip:while(true){(b=(b&&((proc.call)(false,x))));if(!((!b)===false)){(cont=false);break skip;}else ;;(xs_76=(cdr(xs_76)));break skip;};;return undefined;})((car(xs_76))));};undefined;}return b;})(true));})()));})(arguments.length));};
function ormap(proc,xs,ys,zs){return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?(((false||(t===0))===false)?((function(){return (1/0);})()):((function(){return (error("ormap","expected at least two arguments"));})())):((function(){return ((function(b){{var xs_85=xs,xs_86=ys,xs_87=zs,cont=true;while((true&&cont&&(!(null_p(xs_85)))&&(!(null_p(xs_86)))&&(!(null_p(xs_87))))){((function(x,y,z){skip:while(true){(b=(b||((proc.call)(false,x,y,z))));if(!(b===false)){(cont=false);break skip;}else ;;(xs_85=(cdr(xs_85)));(xs_86=(cdr(xs_86)));(xs_87=(cdr(xs_87)));break skip;};;return undefined;})((car(xs_85)),(car(xs_86)),(car(xs_87))));};undefined;}return b;})(false));})())):((function(){return ((function(b){{var xs_83=xs,xs_84=ys,cont=true;while((true&&cont&&(!(null_p(xs_83)))&&(!(null_p(xs_84))))){((function(x,y){skip:while(true){(b=(b||((proc.call)(false,x,y))));if(!(b===false)){(cont=false);break skip;}else ;;(xs_83=(cdr(xs_83)));(xs_84=(cdr(xs_84)));break skip;};;return undefined;})((car(xs_83)),(car(xs_84))));};undefined;}return b;})(false));})())):((function(){return ((function(b){{var xs_82=xs,cont=true;while((true&&cont&&(!(null_p(xs_82))))){((function(x){skip:while(true){(b=(b||((proc.call)(false,x))));if(!(b===false)){(cont=false);break skip;}else ;;(xs_82=(cdr(xs_82)));break skip;};;return undefined;})((car(xs_82))));};undefined;}return b;})(false));})()));})(arguments.length));};
function for_each(proc,xs,ys,zs){return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?(((false||(t===0))===false)?((function(){return (1/0);})()):((function(){return (error("map","expected at least two arguments"));})())):((function(){return ((function(){var xs_91=xs,xs_92=ys,xs_93=zs;while((true&&true&&(!(null_p(xs_91)))&&(!(null_p(xs_92)))&&(!(null_p(xs_93))))){((function(x,y,z){((proc.call)(false,x,y,z));(xs_91=(cdr(xs_91)));(xs_92=(cdr(xs_92)));return (xs_93=(cdr(xs_93)));})((car(xs_91)),(car(xs_92)),(car(xs_93))));};undefined;return undefined;})());})())):((function(){return ((function(){var xs_89=xs,xs_90=ys;while((true&&true&&(!(null_p(xs_89)))&&(!(null_p(xs_90))))){((function(x,y){((proc.call)(false,x,y));(xs_89=(cdr(xs_89)));return (xs_90=(cdr(xs_90)));})((car(xs_89)),(car(xs_90))));};undefined;return undefined;})());})())):((function(){return ((function(){var xs_88=xs;while((true&&true&&(!(null_p(xs_88))))){((function(x){((proc.call)(false,x));return (xs_88=(cdr(xs_88)));})((car(xs_88))));};undefined;return undefined;})());})()));})(arguments.length));};
function filter(pred,xs){var n=(length(xs)),a=(Array(n)),i=0;{var xs_94=xs;while((true&&true&&(!(null_p(xs_94))))){((function(x){var t=((pred.call)(false,x));if(!(t===false)){(a[i]=x);(i+=1);}else ;;return (xs_94=(cdr(xs_94)));})((car(xs_94))));};undefined;}var xs_95=NULL;while((i>0)){(i-=1);(xs_95=(cons(a[i],xs_95)));};return xs_95;};
function list__garray(xs){var a,n=(length(xs));(a=(Array(n)));{var xs_96=xs,i=0;while((true&&true&&(!(null_p(xs_96))))){((function(x){(a[i]=x);(xs_96=(cdr(xs_96)));return (i+=1);})((car(xs_96))));};undefined;}return a;};
function array__glist(axs){var n=axs.length,n_1=(n-1),xs=NULL;{var i=0,t=n;while((true&&true&&(i<t))){((function(i_97){(xs=(cons(axs[(n_1-i_97)],xs)));return (i+=1);})(i));};undefined;}return xs;};
function array_end__glist(axs,from){var n=axs.length,n_1=(n-1),xs=NULL;{var i=0,t=(n_1-from);while((true&&true&&(i<t))){((function(i_98){(xs=(cons(axs[(n_1-i_98)],xs)));return (i+=1);})(i));};undefined;}return xs;};
var empty=NULL;
function cons_p(v){return (pair_p(v));};
function empty_p(v){return (null_p(v));};
function first(xs){return (car(xs));};
function rest(xs){return (cdr(xs));};
function second(xs){return (car((cdr(xs))));};
function third(xs){return (car((cdr((cdr(xs))))));};
function fourth(xs){return (car((cdr((cdr((cdr(xs))))))));};
function fifth(xs){return (car((cdr((cdr((cdr((cdr(xs))))))))));};
function sixth(xs){return (car((cdr((cdr((cdr((cdr((cdr(xs))))))))))));};
function seventh(xs){return (car((cdr((cdr((cdr((cdr((cdr((cdr(xs))))))))))))));};
function eighth(xs){return (car((cdr((cdr((cdr((cdr((cdr((cdr((cdr(xs))))))))))))))));};
function ninth(xs){return (car((cdr((cdr((cdr((cdr((cdr((cdr((cdr((cdr(xs))))))))))))))))));};
function tenth(xs){return (car((cdr((cdr((cdr((cdr((cdr((cdr((cdr((cdr((cdr(xs))))))))))))))))))));};
function last_pair(xs){while((!(null_p((cdr(xs)))))){(xs=(cdr(xs)));};return xs;};
function last(xs){return (car((last_pair(xs))));};
function make_list(k,v){return ((function(xs){{var i=0,t=k;while((true&&true&&(i<t))){((function(i_99){(xs=(cons(v,xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL));};
function vector_p(v){return ((array_p(v))&&(((tag(v))===VECTOR)||((tag(v))===IMMUTABLE_VECTOR)));};
function immutable_vector_p(v){return ((array_p(v))&&((tag(v))===IMMUTABLE_VECTOR));};
function mutable_vector_p(v){return ((array_p(v))&&((tag(v))===VECTOR));};
function make_vector(size,v){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?((function(){return (error("make-vector","expected one or two arguments"));})()):((function(){return (make_vector2(size,v));})())):((function(){return (make_vector2(size,0));})()));})(arguments.length));};
function make_vector2(size,v){var a=(Array((size+1)));(a[0]=VECTOR);{var i=1,t=(size+1);while((true&&true&&(i<t))){((function(i_100){(a[i_100]=v);return (i+=1);})(i));};undefined;}return a;};
function vector(){var args=arguments,n=args.length,a=(Array((n+1)));(a[0]=VECTOR);{var i=0,t=n;while((true&&true&&(i<t))){((function(j){(a[(j+1)]=args[j]);return (i+=1);})(i));};undefined;}return a;};
function vector_immutable(){var args=arguments,n=args.length,a=(Array((n+1)));(a[0]=IMMUTABLE_VECTOR);{var i=0,t=n;while((true&&true&&(i<t))){((function(j){(a[(j+1)]=args[j]);return (i+=1);})(i));};undefined;}return a;};
function vector_length(v){return (v.length-1);};
function vector_ref(v,i){return v[(i+1)];};
function vector_set_e(vec,i,v){return (vec[(i+1)]=v);};
function vector__glist(vec){var n=vec.length,xs=NULL;{var i=1,t=n;while((true&&true&&(i<t))){((function(i_101){(xs=(cons(vec[(n-i_101)],xs)));return (i+=1);})(i));};undefined;}return xs;};
function list__gvector(vs){var n=(length(vs)),vec=(Array((n+1))),i=1;(vec[0]=VECTOR);while((!(null_p(vs)))){(vec[i]=(car(vs)));(i+=1);(vs=(cdr(vs)));};return vec;};
function vector__gimmutable_vector(vec){var n=vec.length,a=(Array(n));(a[0]=IMMUTABLE_VECTOR);{var i=1,t=n;while((true&&true&&(i<t))){((function(j){(a[j]=vec[j]);return (i+=1);})(i));};undefined;}return vec;};
function vector_fill_e(vec,v){var n=vec.length;{var i=1,t=n;while((true&&true&&(i<t))){((function(i_102){(vec[i_102]=v);return (i+=1);})(i));};undefined;}return VOID;};
function vector_copy_e(dest,dest_start,src,src_start,src_end){return ((function(t){return (((false||(t===3))===false)?(((false||(t===4))===false)?(((false||(t===5))===false)?((function(){return (error("vector-copy!","expected 3, 4, or, 5 arguments"));})()):((function(){return (vector_copy_e5(dest,dest_start,src,src_start,src_end));})())):((function(){return (vector_copy_e5(dest,dest_start,src,src_start,(vector_length(src))));})())):((function(){return (vector_copy_e5(dest,dest_start,src,0,(vector_length(src))));})()));})(arguments.length));};
function vector_copy_e5(dest,dest_start,src,src_start,src_end){{var i=dest_start,i_103=src_start,t=src_end;while((true&&true&&true&&(i_103<t))){((function(i_104,j){(dest[i_104]=src[j]);(i+=1);return (i_103+=1);})(i,i_103));};undefined;}return VOID;};
function build_vector(n,proc){var a=(Array((n+1)));(a[0]=VECTOR);{var i=0,t=n;while((true&&true&&(i<t))){((function(i_105){(a[(i_105+1)]=(proc(i_105)));return (i+=1);})(i));};undefined;}return a;};
function box_p(v){return ((array_p(v))&&(((tag(v))===BOX)||((tag(v))===IMMUTABLE_BOX)));};
function box(v){return [BOX,v];};
function box_immutable(v){return [IMMUTABLE_BOX,v];};
function unbox(b){return b[1];};
function set_box_e(b,v){return (b[1]=v);};
function box_cas_e(b,old,new_106){return (((eq_p(b[1],old))===false)?false:((b[1]=new_106),true));};
function immutable_box_p(v){return ((array_p(v))&&((tag(v))===IMMUTABLE_BOX));};
function in_range(start,end,step){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?(((false||(t===3))===false)?((function(){return (("ERROR - in-range - at most 3 arguments")());})()):((function(){return ((((number_p(start))&&(number_p(end))&&(number_p(step)))===false)?(("ERROR - in-range - expected number")()):VOID);})())):((function(){return ((((number_p(start))&&(number_p(end)))===false)?(("ERROR - in-range - expected number")()):VOID);})())):((function(){return (((number_p(start))===false)?(("ERROR - in-range - expected number")()):VOID);})()));})(arguments.length));};
function in_list(xs){return ((function(t){return (((false||(t===1))===false)?((function(){return (("ERROR - in-range - expected 1 argument")());})()):((function(){return (((list_p(xs))===false)?(("ERROR - in-list - expected list")()):VOID);})()));})(arguments.length));};
function closure_p(v){return (((Array["isArray"])(v))&&(v[0]==="CLOS"));};
function procedure_p(v){return (((typeof(v))==="function")||(closure_p(v)));};
function js_function_p(v){return ((typeof(v))==="function");};
function invoke(f){var a,lab,args=arguments,n=args.length;return (((closure_p(f))===false)?((f.apply)(false,args)):((lab=f[1]),(a=(Array((n+1)))),a[0]=f,((function(){var i=0,t=n;while((true&&true&&(i<t))){((function(i_107){(a[(i_107+1)]=args[i_107]);return (i+=1);})(i));};undefined;return undefined;})()),((lab.apply)(false,a))));};
var apply=["CLOS",apply_label];
function apply_label(free,tc,proc,xs){var args=arguments,m=args.length,n=(m-2),tc_108=args[1];return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?(((false||(t===5))===false)?(((false||(t===0)||(t===1))===false)?(((false||(t===6))===false)?undefined:((function(){return (apply3(tc_108,proc,(n-2),((function(a){{var i=2,t_109=(n-2);while((true&&true&&(i<t_109))){((function(i_110){((a.push)(args[i_110]));return (i+=1);})(i));};undefined;}return a;})([])),args[6]));})())):((function(){return (error("procedure?","expected two or more arguments"));})())):((function(){return (apply3(tc_108,proc,3,[args[2],args[3],args[4]],args[6]));})())):((function(){return (apply3(tc_108,proc,2,[args[2],args[3]],args[5]));})())):((function(){return (apply3(tc_108,proc,1,[args[2]],args[4]));})())):((function(){return (apply3(tc_108,proc,0,0,args[3]));})()));})(n));};
function apply3(tc,proc,nvs,vs,xs){var nxs=(length(xs)),n=(nvs+nxs+(((js_function_p(proc))===false)?1:0)),a=(Array(n));return (((js_function_p(proc))===false)?(((closure_p(proc))===false)?"apply3 - error":(a[0]=proc,a[1]=tc,((function(){var i=0,t=nvs;while((true&&true&&(i<t))){((function(i_114){(a[(i_114+2)]=vs[i_114]);return (i+=1);})(i));};undefined;return undefined;})()),((function(){var i=nvs,t=n,xs_115=xs;while((true&&true&&(i<t)&&(!(null_p(xs_115))))){((function(i_116,x){(a[(i_116+2)]=x);(i+=1);return (xs_115=(cdr(xs_115)));})(i,(car(xs_115))));};undefined;return undefined;})()),((proc[1]["apply"])(false,a)))):(((function(){var i=0,t=nvs;while((true&&true&&(i<t))){((function(i_111){(a[i_111]=vs[i_111]);return (i+=1);})(i));};undefined;return undefined;})()),((function(){var i=nvs,t=n,xs_112=xs;while((true&&true&&(i<t)&&(!(null_p(xs_112))))){((function(i_113,x){(a[i_113]=x);(i+=1);return (xs_112=(cdr(xs_112)));})(i,(car(xs_112))));};undefined;return undefined;})()),((proc.apply)(false,a))));};
var new_apply_proc=apply;
function void_p(v){return (v===VOID);};
function Void(){return VOID;};
function struct_type_descriptor_name(std){return std[1];};
function struct_type_descriptor_super(std){return std[2];};
function struct_type_descriptor_total_field_count(std){return std[3];};
function struct_type_descriptor_init_field_indices(std){return std[4];};
function struct_type_descriptor_auto_field_indices(std){return std[5];};
function struct_type_descriptor_auto_field_values(std){return std[6];};
function struct_type_descriptor_properties(std){return std[7];};
function struct_type_descriptor_inspector(std){return std[8];};
function struct_type_descriptor_immutables(std){return std[9];};
function struct_type_descriptor_guard(std){return std[10];};
function struct_type_descriptor_constructor_name(std){return std[11];};
function struct_type_descriptor_p(v){return ((array_p(v))&&(v[0]===STRUCT_TYPE_DESCRIPTOR));};
function struct_p(v){return ((array_p(v))&&(v[0]===STRUCT));};
function str_struct_type_descriptor(s){return ("(struct-type-descriptor "+(str(s[1]))+" "+(str(s[2]))+" "+(str(s[3]))+" "+(str(s[4]))+" "+(str(s[5]))+" "+(str(s[6]))+" "+(str(s[7]))+" "+(str(s[8]))+" "+(str(s[9]))+" "+(str(s[10]))+" "+(str(s[11]))+")");};
function str_struct(s){var n=s.length,fields=((function(a){{var i=2,t=n;while((true&&true&&(i<t))){((function(i_117){((a.push)(s[i_117]));return (i+=1);})(i));};undefined;}return a;})([]));return ("(struct "+(str(s[1]))+" "+((fields.join)(" "))+")");};
function make_struct_type_descriptor(name,super_type,init_field_count,auto_field_count,auto_field_value,props,inspector,proc_spec,immutables,guard,constructor_name){var ifc=init_field_count,afc=auto_field_count,stfc=((super_type===false)?0:(struct_type_descriptor_total_field_count(super_type)));return ((super_type===false)?((function(total_field_count,init_field_indices,auto_field_indices,auto_field_values){return [STRUCT_TYPE_DESCRIPTOR,name,false,total_field_count,init_field_indices,auto_field_indices,auto_field_values,NULL,false,NULL,false,false];})((ifc+afc),((function(xs){{var i=0,t=ifc;while((true&&true&&(i<t))){((function(i_121){(xs=(cons(i_121,xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL)),((function(xs){{var i=0,t=afc;while((true&&true&&(i<t))){((function(i_122){(xs=(cons((ifc+i_122),xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL)),((function(xs){{var i=0,t=afc;while((true&&true&&(i<t))){((function(i_123){(xs=(cons(auto_field_value,xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL)))):((function(total_field_count,new_init_field_indices,new_auto_field_indices,new_auto_field_values){return [STRUCT_TYPE_DESCRIPTOR,name,super_type,total_field_count,(append((struct_type_descriptor_init_field_indices(super_type)),new_init_field_indices)),(append((struct_type_descriptor_auto_field_indices(super_type)),new_auto_field_indices)),(append((struct_type_descriptor_auto_field_values(super_type)),new_auto_field_values)),NULL,false,NULL,false,false];})((ifc+afc+stfc),((function(xs){{var i=0,t=ifc;while((true&&true&&(i<t))){((function(i_118){(xs=(cons((stfc+i_118),xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL)),((function(xs){{var i=0,t=afc;while((true&&true&&(i<t))){((function(i_119){(xs=(cons((stfc+ifc+i_119),xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL)),((function(xs){{var i=0,t=afc;while((true&&true&&(i<t))){((function(i_120){(xs=(cons(auto_field_value,xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL)))));};
function make_struct_type(name,super_type,init_field_count,auto_field_count,auto_value,props,inspector,proc_spec,immutables,guard,constructor_name){return (do_make_struct_type(name,super_type,init_field_count,auto_field_count,(((auto_value===undefined)===false)?auto_value:false),(((props===undefined)===false)?props:NULL),(((inspector===undefined)===false)?inspector:false),(((proc_spec===undefined)===false)?proc_spec:false),(((immutables===undefined)===false)?immutables:NULL),(((guard===undefined)===false)?guard:false),(((constructor_name===undefined)===false)?constructor_name:false)));};
function do_make_struct_type(name,super_type,init_field_count,auto_field_count,auto_field_value,props,inspector,proc_spec,immutables,guard,constructor_name){var super_field_count=((super_type===false)?0:(struct_type_descriptor_total_field_count(super_type))),field_count=(init_field_count+auto_field_count+super_field_count),std=(make_struct_type_descriptor(name,super_type,init_field_count,auto_field_count,auto_field_value,props,inspector,proc_spec,immutables,guard,constructor_name));return ((super_type===false)?(values(std,(function(){var args=arguments,n=arguments.length,a=new Array((n+2));(a[0]=STRUCT);(a[1]=std);{var i=0,t=n;while((true&&true&&(i<t))){((function(i_129){(a[(i_129+2)]=args[i_129]);return (i+=1);})(i));};undefined;}{var i_127=n,t_128=(n+auto_field_count);while((true&&true&&(i_127<t_128))){((function(j){(a[(j+2)]=auto_field_value);return (i_127+=1);})(i_127));};undefined;}return a;}),(function(v){return (v===std);}),(function(s,index){return s[(index+2)];}),(function(s,index,value){(s[(index+2)]=value);return VOID;}))):(values(std,(function(){var args=arguments,n=arguments.length,a=new Array((field_count+2));(a[0]=STRUCT);(a[1]=std);{var xs=(struct_type_descriptor_init_field_indices(std)),i=0,t=n;while((true&&true&&(!(null_p(xs)))&&(i<t))){((function(i_126,j){(a[(i_126+2)]=args[j]);(xs=(cdr(xs)));return (i+=1);})((car(xs)),i));};undefined;}{var xs_124=(struct_type_descriptor_auto_field_indices(std)),xs_125=(struct_type_descriptor_auto_field_values(std));while((true&&true&&(!(null_p(xs_124)))&&(!(null_p(xs_125))))){((function(j,v){(a[(j+2)]=v);(xs_124=(cdr(xs_124)));return (xs_125=(cdr(xs_125)));})((car(xs_124)),(car(xs_125))));};undefined;}return a;}),(function(v){return (v===std);}),(function(s,index){return s[(super_field_count+index+2)];}),(function(s,index,value){(s[(super_field_count+index+2)]=value);return VOID;}))));};
function make_struct_field_accessor(accessor_proc,field_pos,field_name){return (function(s){return (accessor_proc(s,field_pos));});};
function values_p(v){return ((array_p(v))&&((tag(v))===VALUES));};
function values(x){var args=arguments,n=args.length,a;if(!((n===1)===false))(a=x);else {(a=(Array((n+1))));(a[0]=VALUES);{var i=0,t=n;while((true&&true&&(i<t))){((function(j){(a[(j+1)]=args[j]);return (i+=1);})(i));};undefined;}};return a;};
function call_with_values(generator,receiver){var vals=((generator.call)(false));return (((values_p(vals))===false)?((true===false)?undefined:((function(){return ((receiver.apply)(false,vals));})())):((function(){((vals.shift)());return ((receiver.apply)(false,vals));})()));};
function kernel_csrcloc(source,line,column,position,span){return [STRUCT,[STRUCT_TYPE_DESCRIPTOR,"srcloc",false,5,(list(0,1,2,3,4)),NULL,NULL,false,false,NULL,false,"make-srcloc"],source,line,column,position,span];};
function srcloc__gstring(sl){var source=sl[2],line=sl[3],column=sl[4],position=sl[5],span=sl[6];return (source&&(((line&&column)===false)?((line===false)?((position===false)?((true===false)?undefined:((function(){return (string_append(source,"::-1"));})())):((function(){return (string_append(source,"::",position));})())):((function(){return (string_append(source,"::",column));})())):((function(){return (string_append(source,":",line,":",column));})())));};
var the_empty_continuation_mark_set=[];
function empty_continuation_mark_set_p(v){return (v===the_empty_continuation_mark_set);};
function new_continuation_mark_frame(key,val){var frame={};(frame[key]=val);return (CMS=[frame,CMS]);};
function set_continuation_mark(key,val){var frame=CMS[0];(frame[key]=val);return CMS;};
function remove_continuation_mark_frame(){return (CMS=CMS[1]);};
function continuation_mark_set_first(mark_set,key_v,none_v,prompt_tag){var tagged_ms=(mark_set||(current_continuation_marks())),ms=tagged_ms[1],val=undefined,ht=false;while(ms){(ht=ms[0]);(val=ht[key_v]);if(!((val===undefined)===false))(ms=ms[1]);else break;;};return (((val===undefined)===false)?val:(((none_v===undefined)===false)?none_v:false));};
function continuation_mark_set_p(v){return ((array_p(v))&&((tag(v))===CONTINUATION_MARK_SET));};
function current_continuation_marks(prompt_tag){return [CONTINUATION_MARK_SET,CMS];};
function continuation_mark_set__glist(mark_set,key_v,prompt_tag){var ms=mark_set[1],val=undefined,ht=false,xs=NULL;while((!(ms===NULL))){(ht=ms[0]);(val=ht[key_v]);if(!((val===undefined)===false)){}else (xs=(cons(val,xs)));;(ms=ms[1]);};return (reverse(xs));};
function find_parameter_cell(tagged_parameterization,key){var p=(tagged_parameterization&&tagged_parameterization[1]),ht=false,c=false;while(p){(ht=p[0]);(c=ht[key]);if(!((c===undefined)===false)){}else return c;;(p=p[1]);};return false;};
var parameter_count=0;
function make_parameter(v,opt_guard){var guard=(((opt_guard===undefined)===false)?opt_guard:false),key=[("parameter-key-"+parameter_count)],lab=false;(parameter_count+=1);(lab=(function(param,tc,opt_val){var n=arguments.length,p=(continuation_mark_set_first(false,parameterization_key,false)),c=(find_parameter_cell(p,key)),ht=false;return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?undefined:((function(){return ((c===false)?((function(){(c=[opt_val]);(ht=TOP_CMS[0][parameterization_key][1][0]);(ht[key]=c);return VOID;})()):((function(){(c[0]=opt_val);return VOID;})()));})())):((function(){return ((c===false)?v:c[0]);})()));})(n));}));return [CLOS,lab,PARAMETER,key,guard];};
function parameter_p(v){return ((closure_p(v))&&(v[2]===PARAMETER));};
function get_current_parameterization(){var p=(continuation_mark_set_first(false,parameterization_key,false));return p;};
function parameterization_p(v){return ((array_p(v))&&(v[0]===PARAMETERIZATION));};
function current_parameterization(){var p=(continuation_mark_set_first(false,parameterization_key,false));return [PARAMETERIZATION,p];};
function extend_parameterization(tagged_p,param,val){var p=tagged_p[1],key=param[3],cell=[val],ht=[];(ht[key]=cell);return [PARAMETERIZATION,[ht,p]];};
var eof=EOF_OBJECT;
function eof_object_p(v){return (v===EOF_OBJECT);};
function string_port_p(p){return ((array_p(p))&&((tag(p))===STRING_PORT));};
function make_initial_location(){return [1,0,1];};
function port_count_lines_e(port){return VOID;};
function port_next_location(p){var loc=p[5],line=loc[0],col=loc[1],pos=loc[2];return [VALUES,line,col,pos];};
function open_input_string(str_130,name){if(!((name===undefined)===false))(name=false);else ;;return [STRING_PORT,str_130,name,(string_length(str_130)),0,(make_initial_location())];};
function file_position(port,new_pos){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?((function(){return (("ERROR - file-position expected 1 or 2 arguments")());})()):((function(){return (file_position(port,new_pos));})())):((function(){return (file_position(port,false));})()));})(arguments.length));};
function file_position2(port,new_pos){(((!(string_port_p(port)))===false)?undefined:((function(){return (("error 'file-position expected string-input-port, got: ")(port));})()));return (((string_port_p(port))===false)?((true===false)?undefined:((function(){return (("ERROR")());})())):((function(){var str_131=port[1],name=port[2],len=port[3],idx=port[4],loc=port[5];return (((eq_p(new_pos,false))===false)?(((eof_object_p(new_pos))===false)?((((integer_p(new_pos))&&(new_pos>len))===false)?((((integer_p(new_pos))&&(0<=new_pos))===false)?((true===false)?undefined:((function(){return (("error 'file-position expected eof-object or non-negative integer new-pos")());})())):((function(){port[4]=new_pos;return loc[2]=new_pos;})())):((function(){port[4]=new_pos;return loc[2]=new_pos;})())):((function(){port[4]=len;return loc[2]=len;})())):((function(){return idx;})()));})()));};
function displayln(v){return ((console.log)((str(v))));};
function newline(){return ((console.log)(""));};
function display(v){return ((process.stdout.write)((str(v))));};
function write(v){return ((process.stdout.write)((str(v))));};
function console_log(str_132){return ((console.log)(str_132));};
function namespace_p(v){return ((array_p(v))&&((tag(v))===NAMESPACE));};
function make_empty_namespace(){return [NAMESPACE,[],0,[]];};
var CURRENT_NAMESPACE=(make_empty_namespace());
function current_namespace(ns){return ((function(t){return (((false||(t===0))===false)?(((false||(t===1))===false)?((function(){return "ERROR current-namespace expected at most 1 argument";})()):((function(){return (CURRENT_NAMESPACE=ns);})())):((function(){return CURRENT_NAMESPACE;})()));})(arguments.length));};
function namespace_base_phase(opt_ns){var ns=(opt_ns||CURRENT_NAMESPACE);return ns[2];};
function namespace_variable_value(sym,use_mapping_p,failure_thunk,namespace){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?((function(){return (("ERROR - namespace-variable-value - expected at most 4 arguments")());})()):((function(){var dict=namespace[3],val=dict[sym];((use_mapping_p===false)?undefined:((function(){return (("ERROR - namespace-variable-value - TODO map?")());})()));return (((val===undefined)===false)?val:(invoke(failure_thunk)));})())):((function(){var dict=CURRENT_NAMESPACE[3],val=dict[sym];((use_mapping_p===false)?undefined:((function(){return (("ERROR - namespace-variable-value - TODO map?")());})()));return (((val===undefined)===false)?val:(invoke(failure_thunk)));})())):((function(){var dict=CURRENT_NAMESPACE[3],val=dict[sym];((use_mapping_p===false)?undefined:((function(){return (("ERROR - namespace-variable-value - TODO map?")());})()));return (((val===undefined)===false)?val:(("ERROR - namespace-variable-value - no value found: ")()));})())):((function(){var dict=CURRENT_NAMESPACE[3],val=dict[sym];return (((val===undefined)===false)?val:(("ERROR - namespace-variable-value - no value found: ")()));})()));})(arguments.length));};
function namespace_set_variable_value_e(sym,v,map_p,ns){return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?((function(){return (("ERROR - namespace-set-variable-value! - expected at most 4 arguments")());})()):((function(){var dict=ns[3];dict[sym]=v;((map_p===false)?undefined:((function(){return (("ERROR - namespace-set-variable-value! - TODO map?")());})()));return VOID;})())):((function(){var dict=CURRENT_NAMESPACE[3];dict[sym]=v;((map_p===false)?undefined:((function(){return (("ERROR - namespace-set-variable-value! - TODO map?")());})()));return VOID;})())):((function(){var dict=CURRENT_NAMESPACE[3];dict[sym]=v;return VOID;})()));})(arguments.length));};
function namespace_undefine_variable_e(sym,ns){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?undefined:((function(){var dict=ns[3],i=((dict["indexOf"])(sym));((dict.slice)(i,1));return VOID;})())):((function(){return (namespace_undefine_variable_e(sym,CURRENT_NAMESPACE));})()));})(arguments.length));};
function namespace_mapped_symbols(ns){return ((function(t){return (((false||(t===0))===false)?(((false||(t===1))===false)?undefined:((function(){var dict=ns[3];return ((function(xs){{var a=dict,n=a.length,i=0;while((true&&true&&(i<n))){((function(x){(xs=(cons(x,xs)));return (i+=1);})(a[i]));};undefined;}return (reverse(xs));})(NULL));})())):((function(){return (namespace_mapped_symbols(CURRENT_NAMESPACE));})()));})(arguments.length));};
function namespace_module_registry(ns){return ns[1];};
function current_inspector(){return false;};
function unsafe_fx_l(x,y){return (x<y);};
function unsafe_fx_g(x,y){return (x>y);};
function unsafe_fx_a(x,y){return (x+y);};
function unsafe_fx_(x,y){return (x-y);};
function unsafe_fx_m(x,y){return (x*y);};
function unsafe_vector_m_length(v){return (v.length-1);};
function str_null(){return "()";};
function str_number(v){return ((v["toString"])());};
function str_string(v){var s=(((mutable_string_p(v))===false)?v:(string__gimmutable_string(v)));return ("\""+s+"\"");};
function str_list(v){var a=((function(a){{var xs=v;while((true&&true&&(!(null_p(xs))))){((function(x){((a.push)((str(x))));return (xs=(cdr(xs)));})((car(xs))));};undefined;}return a;})([]));return ("("+((a.join)(" "))+")");};
function str_vector(v){var a=((function(a){{var xs=v,n=(vector_length(xs)),i=0;while((true&&true&&(i<n))){((function(x){((a.push)((str(x))));return (i+=1);})(xs[(i+1)]));};undefined;}return a;})([]));return ("#("+((a.join)(" "))+")");};
function str_pair(v){return ("("+(str((car(v))))+" . "+(str((cdr(v))))+")");};
function str_boolean(v){return (((v===true)===false)?(((v===false)===false)?((true===false)?undefined:((function(){return ("str -internal error got: "+v);})())):((function(){return "#f";})())):((function(){return "#t";})()));};
function str_symbol(v){return (string_append("'",(string__gimmutable_string((symbol__gstring(v))))));};
function str_keyword(v){return ("#:"+v[1]);};
function str_void(v){return "#<void>";};
function str_box(v){return ("#&"+(str((unbox(v)))));};
function str_box_immutable(v){return ("#&"+(str((unbox(v)))));};
function str_char(v){return ("#\\"+v[1]);};
function str_undefined(){return "#<js-undefined>";};
function str_continuation_mark_set(v){((console.log)(v));return "#<continuation-mark-set>";};
function str_parameterization(v){((console.log)(v));return "#<parameterization>";};
function str_parameter(v){((console.log)(v));return "#<parameter>";};
function str(v){return (((null_p(v))===false)?(((string_p(v))===false)?(((number_p(v))===false)?(((list_p(v))===false)?(((pair_p(v))===false)?(((vector_p(v))===false)?(((boolean_p(v))===false)?(((symbol_p(v))===false)?(((keyword_p(v))===false)?(((void_p(v))===false)?(((immutable_box_p(v))===false)?(((box_p(v))===false)?(((char_p(v))===false)?(((struct_type_descriptor_p(v))===false)?(((struct_p(v))===false)?(((v===undefined)===false)?(((continuation_mark_set_p(v))===false)?(((parameterization_p(v))===false)?(((parameter_p(v))===false)?((true===false)?undefined:((function(){((console.log)(v));return "str - internal error";})())):((function(){return (str_parameter(v));})())):((function(){return (str_parameterization(v));})())):((function(){return (str_continuation_mark_set(v));})())):((function(){return (str_undefined());})())):((function(){return (str_struct(v));})())):((function(){return (str_struct_type_descriptor(v));})())):((function(){return (str_char(v));})())):((function(){return (str_box(v));})())):((function(){return (str_box_immutable(v));})())):((function(){return (str_void(v));})())):((function(){return (str_keyword(v));})())):((function(){return (str_symbol(v));})())):((function(){return (str_boolean(v));})())):((function(){return (str_vector(v));})())):((function(){return (str_pair(v));})())):((function(){return (str_list(v));})())):((function(){return (str_number(v));})())):((function(){return (str_string(v));})())):((function(){return (str_null());})()));};
exports.PRIM_q=PRIM_q;
exports.make_string=make_string;
exports.symbol_interned_p=symbol_interned_p;
exports.cos=cos;
exports.image_part=image_part;
exports.struct_type_descriptor_total_field_count=struct_type_descriptor_total_field_count;
exports.namespace_undefine_variable_e=namespace_undefine_variable_e;
exports.bytes_copy=bytes_copy;
exports.symbol_eq_p=symbol_eq_p;
exports.make_bytes1=make_bytes1;
exports.pseudo_random_generator_vector_p=pseudo_random_generator_vector_p;
exports.cons_p=cons_p;
exports.namespace_module_registry=namespace_module_registry;
exports.NAMESPACE=NAMESPACE;
exports.car=car;
exports.IMMUTABLE_BOX=IMMUTABLE_BOX;
exports.sqrt=sqrt;
exports.namespace_variable_value=namespace_variable_value;
exports.vector_immutable=vector_immutable;
exports.number_p=number_p;
exports.make_parameter=make_parameter;
exports.make_char=make_char;
exports.current_parameterization=current_parameterization;
exports.null_p=null_p;
exports.infinite_p=infinite_p;
exports.boolean_p=boolean_p;
exports.apply=apply;
exports.symbol__gimmutable_string=symbol__gimmutable_string;
exports.BYTES=BYTES;
exports.gcd=gcd;
exports.KEYWORD=KEYWORD;
exports.symbol_p=symbol_p;
exports.parameter_p=parameter_p;
exports.$_=$_;
exports.vector__gimmutable_vector=vector__gimmutable_vector;
exports.dispatch_case_lambda=dispatch_case_lambda;
exports.string_upcase=string_upcase;
exports.random_seed=random_seed;
exports.fifth=fifth;
exports.integer_sqrt=integer_sqrt;
exports.make_pseudo_random_generator=make_pseudo_random_generator;
exports.new_continuation_mark_frame=new_continuation_mark_frame;
exports.string_g_eq_p=string_g_eq_p;
exports.unsafe_fx_g=unsafe_fx_g;
exports.box=box;
exports.SYMBOL=SYMBOL;
exports.integer__gchar=integer__gchar;
exports.char_p=char_p;
exports.build_list=build_list;
exports.char_eq_p=char_eq_p;
exports.floor=floor;
exports.ceiling=ceiling;
exports.vector__gpseudo_random_generator=vector__gpseudo_random_generator;
exports.string_set_e=string_set_e;
exports.string__glist=string__glist;
exports.flonum_p=flonum_p;
exports.abs=abs;
exports.struct_type_descriptor_auto_field_indices=struct_type_descriptor_auto_field_indices;
exports.exact_positive_integer_p=exact_positive_integer_p;
exports.subbytes3=subbytes3;
exports.eof_object_p=eof_object_p;
exports.map=map;
exports.list__gvector=list__gvector;
exports.current_continuation_marks=current_continuation_marks;
exports.unsafe_cdr=unsafe_cdr;
exports.struct_type_descriptor_guard=struct_type_descriptor_guard;
exports.min=min;
exports.acos=acos;
exports.integer_p=integer_p;
exports.eqv_p=eqv_p;
exports.PRIM_l=PRIM_l;
exports.unsafe_fx_l=unsafe_fx_l;
exports.string_append=string_append;
exports.real__gsingle_flonum=real__gsingle_flonum;
exports.real__gdouble_flonum=real__gdouble_flonum;
exports.asin=asin;
exports.gensym_counter=gensym_counter;
exports.srcloc__gstring=srcloc__gstring;
exports.vector_length=vector_length;
exports.values_p=values_p;
exports.make_primitive_string=make_primitive_string;
exports.set_continuation_mark=set_continuation_mark;
exports.PRIM_m=PRIM_m;
exports.gcd2=gcd2;
exports.vector_copy_e=vector_copy_e;
exports.number__gstring=number__gstring;
exports.make_bytes=make_bytes;
exports.bytes=bytes;
exports.current_namespace=current_namespace;
exports.vector__glist=vector__glist;
exports.closure_p=closure_p;
exports.substring=substring;
exports.vector_ref=vector_ref;
exports.substring2=substring2;
exports.PARAMETER=PARAMETER;
exports.error=error;
exports.in_list=in_list;
exports.bytes__gInt8Array=bytes__gInt8Array;
exports.last_pair=last_pair;
exports.string__gsymbol=string__gsymbol;
exports.VECTOR=VECTOR;
exports.MUTABLE_BYTES=MUTABLE_BYTES;
exports.mutable_string_p=mutable_string_p;
exports.kernel_csrcloc=kernel_csrcloc;
exports.IMMUTABLE_VECTOR=IMMUTABLE_VECTOR;
exports.make_string1=make_string1;
exports.immutable_bytes_p=immutable_bytes_p;
exports.PRIM_g=PRIM_g;
exports.unbox=unbox;
exports.void_p=void_p;
exports.VOID=VOID;
exports.first=first;
exports.parameterization_p=parameterization_p;
exports.Void=Void;
exports.keyword_l_p=keyword_l_p;
exports.immutable_string_p=immutable_string_p;
exports.$_a=$_a;
exports.namespace_set_variable_value_e=namespace_set_variable_value_e;
exports.STRUCT_TYPE_DESCRIPTOR=STRUCT_TYPE_DESCRIPTOR;
exports.inexact_p=inexact_p;
exports.console_log=console_log;
exports.positive_p=positive_p;
exports.max=max;
exports.keyword_p=keyword_p;
exports.PRIM_not=PRIM_not;
exports.fixnum_p=fixnum_p;
exports.CHAR=CHAR;
exports.unsafe_fx_m=unsafe_fx_m;
exports.andmap=andmap;
exports.struct_type_descriptor_properties=struct_type_descriptor_properties;
exports.PAIR=PAIR;
exports.equal_p=equal_p;
exports.str_struct=str_struct;
exports.str=str;
exports.string__gkeyword=string__gkeyword;
exports.call_with_values=call_with_values;
exports.struct_type_descriptor_name=struct_type_descriptor_name;
exports.rest=rest;
exports.STRING_PORT=STRING_PORT;
exports.integer_sqrt_qremainder=integer_sqrt_qremainder;
exports.symbol__gstring=symbol__gstring;
exports.continuation_mark_set_first=continuation_mark_set_first;
exports.extend_parameterization=extend_parameterization;
exports.log=log;
exports.make_struct_field_accessor=make_struct_field_accessor;
exports.namespace_base_phase=namespace_base_phase;
exports.pair_p=pair_p;
exports.atan=atan;
exports.cdr=cdr;
exports.tenth=tenth;
exports.real_p=real_p;
exports.build_vector=build_vector;
exports.PARAMETERIZATION=PARAMETERIZATION;
exports.$_m=$_m;
exports.parameterization_key=parameterization_key;
exports.random=random;
exports.list_tail=list_tail;
exports.angle=angle;
exports.current_inspector=current_inspector;
exports.make_empty_namespace=make_empty_namespace;
exports.vector=vector;
exports.quotient_qremainder=quotient_qremainder;
exports.list_m=list_m;
exports.string__gimmutable_string=string__gimmutable_string;
exports.add1=add1;
exports.NULL=NULL;
exports.write=write;
exports.sixth=sixth;
exports.namespace_mapped_symbols=namespace_mapped_symbols;
exports.struct_type_descriptor_immutables=struct_type_descriptor_immutables;
exports.do_make_struct_type=do_make_struct_type;
exports.byte_p=byte_p;
exports.substring3=substring3;
exports.zero_p=zero_p;
exports.seventh=seventh;
exports.filter=filter;
exports.exact__ginexact=exact__ginexact;
exports.make_struct_type=make_struct_type;
exports.port_next_location=port_next_location;
exports.string__guninterned_symbol=string__guninterned_symbol;
exports.bytes_p=bytes_p;
exports.bytes_ref=bytes_ref;
exports.box_immutable=box_immutable;
exports.display=display;
exports.VALUES=VALUES;
exports.continuation_mark_set_p=continuation_mark_set_p;
exports.current_pseudo_random_generator=current_pseudo_random_generator;
exports.namespace_p=namespace_p;
exports.vector_set_e=vector_set_e;
exports.reverse=reverse;
exports.alt_reverse=alt_reverse;
exports.PRIM_eq=PRIM_eq;
exports.PRIM_=PRIM_;
exports.new_apply_proc=new_apply_proc;
exports.ninth=ninth;
exports.round=round;
exports.negative_p=negative_p;
exports.PRIM_a=PRIM_a;
exports.nan_p=nan_p;
exports.values=values;
exports.rational_p=rational_p;
exports.even_p=even_p;
exports.vector__gpseudo_random_generator_e=vector__gpseudo_random_generator_e;
exports.CLOS=CLOS;
exports.truncate=truncate;
exports.list_p=list_p;
exports.EOF_OBJECT=EOF_OBJECT;
exports.append2=append2;
exports.STRUCT=STRUCT;
exports.remainder=remainder;
exports.displayln=displayln;
exports.string_g_p=string_g_p;
exports.struct_type_descriptor_inspector=struct_type_descriptor_inspector;
exports.PRIM_l_eq=PRIM_l_eq;
exports.string_eq_p=string_eq_p;
exports.fourth=fourth;
exports.remove_continuation_mark_frame=remove_continuation_mark_frame;
exports.magnitude=magnitude;
exports.string_port_p=string_port_p;
exports.odd_p=odd_p;
exports.CONTINUATION_MARK_SET=CONTINUATION_MARK_SET;
exports.bytes_length=bytes_length;
exports.string_l_p=string_l_p;
exports.array__glist=array__glist;
exports.bytes_eq_p=bytes_eq_p;
exports.inexact_real_p=inexact_real_p;
exports.struct_type_descriptor_p=struct_type_descriptor_p;
exports.exact_integer_p=exact_integer_p;
exports.make_vector=make_vector;
exports.tan=tan;
exports.pi=pi;
exports.string_length=string_length;
exports.list_ref=list_ref;
exports.box_cas_e=box_cas_e;
exports.for_each=for_each;
exports.set_box_e=set_box_e;
exports.cons=cons;
exports.sin=sin;
exports.keyword__gstring=keyword__gstring;
exports.newline=newline;
exports.in_range=in_range;
exports.empty_p=empty_p;
exports.string__gnumber=string__gnumber;
exports.struct_type_descriptor_super=struct_type_descriptor_super;
exports.make_list=make_list;
exports.string_p=string_p;
exports.sub1=sub1;
exports.mutable_bytes_p=mutable_bytes_p;
exports.CURRENT_NAMESPACE=CURRENT_NAMESPACE;
exports.pseudo_random_generator__gvector=pseudo_random_generator__gvector;
exports.length=length;
exports.port_count_lines_e=port_count_lines_e;
exports.quotient=quotient;
exports.unsafe_vector_m_length=unsafe_vector_m_length;
exports.str_struct_type_descriptor=str_struct_type_descriptor;
exports.struct_p=struct_p;
exports.struct_type_descriptor_init_field_indices=struct_type_descriptor_init_field_indices;
exports.array_end__glist=array_end__glist;
exports.bytes__gimmutable_bytes=bytes__gimmutable_bytes;
exports.exact_p=exact_p;
exports.CMS=CMS;
exports.$_q=$_q;
exports.eq_p=eq_p;
exports.modulo=modulo;
exports.keyword_eq_p=keyword_eq_p;
exports.make_string2=make_string2;
exports.BOX=BOX;
exports.immutable_vector_p=immutable_vector_p;
exports.list=list;
exports.string_l_eq_p=string_l_eq_p;
exports.ormap=ormap;
exports.append=append;
exports.string=string;
exports.make_struct_type_descriptor=make_struct_type_descriptor;
exports.immutable_string__gstring=immutable_string__gstring;
exports.eof=eof;
exports.make_bytes2=make_bytes2;
exports.struct_type_descriptor_constructor_name=struct_type_descriptor_constructor_name;
exports.eighth=eighth;
exports.continuation_mark_set__glist=continuation_mark_set__glist;
exports.list__garray=list__garray;
exports.cddr=cddr;
exports.exp=exp;
exports.unsafe_fx_a=unsafe_fx_a;
exports.immutable_p=immutable_p;
exports.complex_p=complex_p;
exports.bytes_set_e=bytes_set_e;
exports.third=third;
exports.array_p=array_p;
exports.vector_fill_e=vector_fill_e;
exports.expt=expt;
exports.second=second;
exports.subbytes2=subbytes2;
exports.struct_type_descriptor_auto_field_values=struct_type_descriptor_auto_field_values;
exports.gensym=gensym;
exports.PRIM_g_eq=PRIM_g_eq;
exports.MUTABLE_STRING=MUTABLE_STRING;
exports.procedure_p=procedure_p;
exports.pseudo_random_generator_p=pseudo_random_generator_p;
exports.subbytes=subbytes;
exports.unsafe_car=unsafe_car;
exports.inexact__gexact=inexact__gexact;
exports.double_flonum_p=double_flonum_p;
exports.tag=tag;
exports.single_flonum_p=single_flonum_p;
exports.empty=empty;
exports.real_part=real_part;
exports.immutable_box_p=immutable_box_p;
exports.immutable_bytes__gbytes=immutable_bytes__gbytes;
exports.char__ginteger=char__ginteger;
exports.exact_nonnegative_integer_p=exact_nonnegative_integer_p;
exports.string_append2=string_append2;
exports.last=last;
exports.string_ref=string_ref;
exports.vector_p=vector_p;
exports.symbol_l_p=symbol_l_p;
exports.mutable_vector_p=mutable_vector_p;
exports.Null=Null;
exports.unsafe_fx_=unsafe_fx_;
exports.box_p=box_p;
