"use strict";
function array_p(v){return (Array.isArray(v));};
function tag(a){return a[0];};
var PAIR=["pair"];
var VECTOR=["vector"];
var IMMUTABLE_VECTOR=["immutable-vector"];
var BOX=["box"];
var IMMUTABLE_BOX=["immutable-box"];
var CHAR=["char"];
var MUTABLE_STRING=["mutable-string"];
var BYTES=["bytes"];
var MUTABLE_BYTES=["mutable-bytes"];
var SYMBOL=["symbol"];
var KEYWORD=["keyword"];
var VALUES=["values"];
var STRUCT_TYPE_DESCRIPTOR=["struct-type-descriptor"];
var STRUCT=["struct"];
var VOID=[];
var NULL=[];
function boolean_p(v){return ((typeof(v))==="boolean");};
function equal_p(v,w){return ((((boolean_p(v))&&(boolean_p(w)))===false)?((((number_p(v))&&(number_p(w)))===false)?((((symbol_p(v))&&(symbol_p(w)))===false)?((((null_p(v))&&(null_p(w)))===false)?((((pair_p(v))&&(pair_p(w)))===false)?((((void_p(v))&&(void_p(w)))===false)?((((char_p(v))&&(char_p(w)))===false)?((((immutable_string_p(v))&&(immutable_string_p(w)))===false)?((((mutable_string_p(v))&&(mutable_string_p(w)))===false)?((((vector_p(v))&&(vector_p(w)))===false)?((((box_p(v))&&(box_p(w)))===false)?((((bytes_p(v))&&(bytes_p(w)))===false)?((((keyword_p(v))&&(keyword_p(w)))===false)?((true===false)?undefined:((function(){return false;})())):((function(){return (keyword_eq_p(v,w));})())):((function(){return (bytes_eq_p(v,w));})())):((function(){return (equal_p((unbox(v)),(unbox(w))));})())):((function(){return ((function(b){{var xs=v,n=(vector_length(xs)),i=0,xs_3=w,n_2=(vector_length(xs_3)),i_1=0,cont=true;while((true&&cont&&(i<n)&&(i_1<n_2))){((function(x,y){skip:while(true){(b=(b&&(equal_p(x,y))));if(!((!b)===false)){(cont=false);break skip;}else ;;(i+=1);(i_1+=1);break skip;};;return undefined;})(xs[(i+1)],xs_3[(i_1+1)]));};undefined;}return b;})(true));})())):((function(){return (string_eq_p(v,w));})())):((function(){return (v===w);})())):((function(){return (char_eq_p(v,w));})())):((function(){return true;})())):((function(){return ((equal_p((unsafe_car(v)),(unsafe_car(w))))&&(equal_p((unsafe_cdr(v)),(unsafe_cdr(w)))));})())):((function(){return true;})())):((function(){return (symbol_eq_p(v,w));})())):((function(){return (v===w);})())):((function(){return (v===w);})()));};
function eqv_p(v,w){return ((((number_p(v))&&(number_p(w)))===false)?((((char_p(v))&&(char_p(w)))===false)?((true===false)?undefined:((function(){return (v===w);})())):((function(){return ((char__ginteger(v))===(char__ginteger(w)));})())):((function(){return (v===w);})()));};
function eq_p(v1,v2){return (v1===v2);};
function immutable_p(v){return ((immutable_string_p(v))||(immutable_bytes_p(v))||(immutable_vector_p(v))||(immutable_box_p(v)));};
function number_p(v){return ((typeof(v))==="number");};
function complex_p(v){return (number_p(v));};
function real_p(v){return (number_p(v));};
function rational_p(v){return ((number_p(v))&&(Number.isFinite(v)));};
function integer_p(v){return (Number.isInteger(v));};
function exact_integer_p(v){return (((typeof(v))==="number")&&(v===(+v))&&(v===(v|0)));};
function exact_nonnegative_integer_p(v){return ((exact_integer_p(v))&&(v>=0));};
function exact_positive_integer_p(v){return ((exact_integer_p(v))&&(v>0));};
function inexact_real_p(v){return ((real_p(v))&&(inexact_p(v)));};
function fixnum_p(v){return (exact_integer_p(v));};
function flonum_p(v){return ((number_p(v))&&(!(exact_integer_p(v))));};
function double_flonum_p(v){return (flonum_p(v));};
function single_flonum_p(v){return (flonum_p(v));};
function zero_p(z){return (z===0);};
function positive_p(x){return (x>0);};
function negative_p(x){return (x<0);};
function even_p(n){return (0===(n%2));};
function odd_p(n){return (1===(n%2));};
function exact_p(z){return (exact_integer_p(z));};
function inexact_p(z){return ((number_p(z))&&(!(exact_p(z))));};
function inexact__gexact(z){return z;};
function exact__ginexact(z){return z;};
function real__gsingle_flonum(x){return x;};
function real__gdouble_flonum(x){return x;};
function $_a(z1,z2){var n=arguments.length,res;if(!((n===2)===false))(res=(z1+z2));else if(!((n===1)===false))(res=z1);else if(!((n===0)===false))(res=0);else {var sum=(z1+z2),i=2,args=arguments;while((i<n)){(sum+=args[i]);(i+=1);};(res=sum);};;;return res;};
function $_(z1,z2){var n=arguments.length,res;if(!((n===2)===false))(res=(z1-z2));else if(!((n===1)===false))(res=(-z1));else {var sum=(z1-z2),i=2,args=arguments;while((i<n)){(sum-=args[i]);(i+=1);};(res=sum);};;return res;};
function $_m(z1,z2){var n=arguments.length,res;if(!((n===2)===false))(res=(z1*z2));else if(!((n===1)===false))(res=z1);else if(!((n===0)===false))(res=1);else {var prod=(z1*z2),i=2,args=arguments;while((i<n)){(prod*=args[i]);(i+=1);};(res=prod);};;;return res;};
function $_q(z1,z2){var n=arguments.length,res;if(!((n===2)===false))(res=(z1/z2));else if(!((n===1)===false))(res=(1/z1));else {var quot=(z1/z2),i=2,args=arguments;while((i<n)){(quot/=args[i]);(i+=1);};(res=quot);};;return res;};
function quotient(n,m){return (Math.floor((n/m)));};
function remainder(n,m){return (n%m);};
function quotient_qremainder(n,m){return (values((quotient(n,m)),(remainder(n,m))));};
function modulo(n,m){return (((n%m)+m)%m);};
function add1(z){return (z+1);};
function sub1(z){return (z-1);};
function abs(x){return (Math.abs(x));};
function max(){return ((Math.max.apply)(false,arguments));};
function min(){return ((Math.min.apply)(false,arguments));};
function gcd(n,m){var args=arguments,i,g,l;return ((function(t){return (((false||(t===2))===false)?(((false||(t===1))===false)?(((false||(t===0))===false)?((function(){(l=args.length);(g=args[0]);{var i_4=1,t_5=l;while((true&&true&&(i_4<t_5))){((function(i_6){(g=(gcd(g,args[i_6])));return (i_4+=1);})(i_4));};undefined;}return g;})()):((function(){return 0;})())):((function(){return n;})())):((function(){return (gcd2(n,m));})()));})(arguments.length));};
function gcd2(n,m){var a,b;if(!((n<0)===false)){(n=(-n));}else ;;if(!((m<0)===false)){(m=(-m));}else ;;(a=(((n>m)===false)?m:n));(b=(((n<m)===false)?m:n));var res=false;while((!res)){(((b===0)===false)?((true===false)?undefined:((function(){(a%=b);return (((a===0)===false)?((true===false)?undefined:((function(){return (b%=a);})())):((function(){return (res=b);})()));})())):((function(){return (res=a);})()));};return res;};
function round(x){var r=(Math.round(x));return (((((((x>0)===false)?(-x):x)%1)===0.5)===false)?r:(((even_p(r))===false)?(r-1):r));};
function floor(x){return (Math.floor(x));};
function ceiling(x){return (Math.ceil(x));};
function truncate(x){return (Math.trunc(x));};
function sqrt(x){return (Math.sqrt(x));};
function integer_sqrt(n){return (Math.floor((Math.sqrt(n))));};
function integer_sqrt_qremainder(n){var s=(Math.floor((Math.sqrt(n))));return (values(s,(n-(s*s))));};
function expt(z,w){return (Math.pow(z,w));};
function exp(z){return (Math.exp(z));};
function log(z){return (Math.log(z));};
function sin(z){return (Math.sin(z));};
function cos(z){return (Math.sin(z));};
function tan(z){return (Math.tan(z));};
function asin(z){return (Math.asin(z));};
function acos(z){return (Math.acos(z));};
function atan(y,x){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?((function(){return "error: atan - todo - raise exception";})()):((function(){return (Math.atan(y,x));})())):((function(){return (Math.atan(y));})()));})(arguments.length));};
function real_part(z){return z;};
function image_part(z){return 0;};
function magnitude(z){return (Math.abs(z));};
function angle(z){return (((z>0)===false)?(((z<0)===false)?((true===false)?undefined:((function(){return (error("angle","undefined for 0"));})())):((function(){return Math.PI;})())):((function(){return 0;})()));};
function random(k,rand_gen){return (Math.floor(((Math.random())*k)));};
function random_seed(k){return (Void());};
function make_pseudo_random_generator(){return false;};
function pseudo_random_generator_p(v){return (eq_p(v,false));};
function current_pseudo_random_generator(rand_gen){return false;};
function pseudo_random_generator__gvector(rand_gen){return (vector());};
function vector__gpseudo_random_generator(vec){return false;};
function vector__gpseudo_random_generator_e(rand_gen,vec){return (Void());};
function pseudo_random_generator_vector_p(v){return (vector_p(v));};
function number__gstring(z,radix){var num=(Number(z));return (num.toString(radix));};
function string__gnumber(s,radix){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?((function(){return (error("string->number","expected one or two arguments"));})()):((function(){return (parseFloat(s,radix));})())):((function(){return (parseFloat(s));})()));})(arguments.length));};
var pi=Math.PI;
function nan_p(x){return (x===NaN);};
function infinite_p(x){return ((x===Infinity)||(x===(-Infinity)));};
function string_p(v){return (((typeof(v))==="string")||((array_p(v))&&((tag(v))===MUTABLE_STRING)));};
function immutable_string_p(v){return ((typeof(v))==="string");};
function mutable_string_p(v){return ((array_p(v))&&((tag(v))===MUTABLE_STRING));};
function make_string(k,ch){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?((function(){return (error("make-string","expected at one or two argument"));})()):((function(){return (make_string2(k,ch));})())):((function(){return (make_string1(k));})()));})(arguments.length));};
function make_string1(k){return (make_string2(k," "));};
function make_string2(k,ch){var a=(Array((k+1)));(a[0]=MUTABLE_STRING);{var i=1,t=(k+1);while((true&&true&&(i<t))){((function(i_7){(a[i_7]=ch[1]);return (i+=1);})(i));};undefined;}return a;};
function make_primitive_string(n,c){var s="";while(true){if(!((!((n&1)===0))===false)){(s+=c);}else ;;(n>>=1);if(!((n===0)===false))break;else (c+=c);;};return s;};
function string__gimmutable_string(s){return ((((typeof(s))==="string")===false)?((true===false)?undefined:((function(){var n_a1=s.length,n=(n_a1-1),a=(Array(n));{var i=0,t=n;while((true&&true&&(i<t))){((function(i_8){(a[i_8]=s[(i_8+1)]);return (i+=1);})(i));};undefined;}return (String((a.join(""))));})())):((function(){return s;})()));};
function immutable_string__gstring(str_9){var n=str_9.length,a=(Array((n+1)));(a[0]=MUTABLE_STRING);{var i=0,t=n;while((true&&true&&(i<t))){((function(i_10){(a[(i_10+1)]=str_9[i_10]);return (i+=1);})(i));};undefined;}return a;};
function string(){var args=arguments,n=args.length;var a=(Array((n+1)));(a[0]=MUTABLE_STRING);{var i=0,t=n;while((true&&true&&(i<t))){((function(i_11){(a[(i_11+1)]=args[i_11][1]);return (i+=1);})(i));};undefined;}return a;};
function string_length(s){return ((((typeof(s))==="string")===false)?(s.length-1):s.length);};
function string_ref(s,i){return ((((typeof(s))==="string")===false)?[CHAR,s[(i+1)]]:[CHAR,s[i]]);};
function string_set_e(s,i,c){return (s[(i+1)]=c[1]);};
function substring3(str_12,start,end){return (str_12.substring(start,end));};
function substring2(str_13,start){return (str_13.substring(start,(string_length(str_13))));};
function substring(){return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?((function(){return (error("substring","expected two to three arguments"));})()):((function(){return (substring3(arguments[0],arguments[1],arguments[2]));})())):((function(){return (substring2(arguments[0],arguments[1]));})()));})(arguments.length));};
function string_eq_p(str1,str2){return (((immutable_string_p(str1))===false)?(((immutable_string_p(str2))===false)?((string__gimmutable_string(str1))===(string__gimmutable_string(str2))):((string__gimmutable_string(str1))===str2)):(((immutable_string_p(str2))===false)?(str1===(string__gimmutable_string(str2))):(str1===str2)));};
function string_l_p(str1,str2){return (((immutable_string_p(str1))===false)?(((immutable_string_p(str2))===false)?((string__gimmutable_string(str1))<(string__gimmutable_string(str2))):((string__gimmutable_string(str1))<str2)):(((immutable_string_p(str2))===false)?(str1<(string__gimmutable_string(str2))):(str1<str2)));};
function string_g_p(str1,str2){return (((immutable_string_p(str1))===false)?(((immutable_string_p(str2))===false)?((string__gimmutable_string(str1))>(string__gimmutable_string(str2))):((string__gimmutable_string(str1))>str2)):(((immutable_string_p(str2))===false)?(str1>(string__gimmutable_string(str2))):(str1>str2)));};
function string_l_eq_p(str1,str2){return (((immutable_string_p(str1))===false)?(((immutable_string_p(str2))===false)?((string__gimmutable_string(str1))<=(string__gimmutable_string(str2))):((string__gimmutable_string(str1))<=str2)):(((immutable_string_p(str2))===false)?(str1<=(string__gimmutable_string(str2))):(str1<=str2)));};
function string_g_eq_p(str1,str2){return (((immutable_string_p(str1))===false)?(((immutable_string_p(str2))===false)?((string__gimmutable_string(str1))>=(string__gimmutable_string(str2))):((string__gimmutable_string(str1))>=str2)):(((immutable_string_p(str2))===false)?(str1>=(string__gimmutable_string(str2))):(str1>=str2)));};
function string_upcase(str_14){return (((immutable_string_p(str_14))===false)?(string_upcase((string__gimmutable_string(str_14)))):(immutable_string__gstring((String((str_14.toUpperCase()))))));};
function string_downcase(str_15){return (((immutable_string_p(str_15))===false)?(string_downcase((string__gimmutable_string(str_15)))):(immutable_string__gstring((String((str_15.toLowerCase()))))));};
function string__glist(s){return ((function(xs){{var s_16=s,n=s_16.length,i=0;while((true&&true&&(i<n))){((function(c){(xs=(cons(c,xs)));return (i+=1);})((string_ref(s_16,i))));};undefined;}return (reverse(xs));})(NULL));};
function string_append2(str1,str2){return (str1.concat(str2));};
function string_append(){var args=arguments;var as=((function(){var n=args.length,a=new Array(n),i=0;{var a_17=args,n_18=a_17.length,i_19=0;while((true&&true&&(i_19<n_18))){((function(a_21){(a[i]=a_21);(i+=1);return (i_19+=1);})(a_17[i_19]));};undefined;}if(!((i<n)===false)){var i_20=i,t=n;while((true&&true&&(i_20<t))){((function(j){a[j]=0;return (i_20+=1);})(i_20));};undefined;}else ;;return a;})());return (as.join(""));};
function bytes_p(v){return ((array_p(v))&&(((tag(v))===BYTES)||((tag(v))===MUTABLE_BYTES)));};
function immutable_bytes_p(v){return ((array_p(v))&&((tag(v))===BYTES));};
function mutable_bytes_p(v){return ((array_p(v))&&((tag(v))===MUTABLE_BYTES));};
function bytes__gInt8Array(bs){return bs[1];};
function make_bytes(k,b){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?((function(){return (error("make-bytes","expected one or two arguments"));})()):((function(){return (make_bytes2(k,b));})())):((function(){return (make_bytes1(k));})()));})(arguments.length));};
function make_bytes1(k){var is=new Int8Array(k);return [MUTABLE_BYTES,is];};
function make_bytes2(k,b){var bs=new Int8Array(k);{var i=0,t=k;while((true&&true&&(i<t))){((function(i_22){(bs[i_22]=b);return (i+=1);})(i));};undefined;}return [MUTABLE_BYTES,bs];};
function bytes(){var args=arguments,n=args.length,is=(Int8Array(n));(is.set(args));return [MUTABLE_BYTES,is];};
function bytes__gimmutable_bytes(bs){return [BYTES,(Int8Array.from(bs[1]))];};
function immutable_bytes__gbytes(bs){return [MUTABLE_BYTES,(Int8Array.from(bs[1]))];};
function byte_p(v){return ((exact_integer_p(v))&&(0<=v<=255));};
function bytes_length(bs){return bs[1].length;};
function bytes_ref(bs,k){return bs[1][k];};
function bytes_set_e(bs,k,b){var is=bs[1];return (is[k]=b);};
function subbytes(bs,start,end){return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?((function(){return (error("subbytes","expected two or three arguments"));})()):((function(){return (subbytes3(bs,start,end));})())):((function(){return (subbytes2(bs,start));})()));})(arguments.length));};
function subbytes2(bs,start){var is=bs[1],end=is.length,k=(end-start),t=new Int8Array(k);{var i=start,t_23=end;while((true&&true&&(i<t_23))){((function(i_24){(t[i_24]=is[i_24]);return (i+=1);})(i));};undefined;}return [MUTABLE_BYTES,is];};
function subbytes3(bs,start,end){var is=bs[1],k=(end-start),t=new Int8Array(k);{var i=start,t_25=end;while((true&&true&&(i<t_25))){((function(i_26){(t[i_26]=is[i_26]);return (i+=1);})(i));};undefined;}return [MUTABLE_BYTES,is];};
function bytes_copy(bs){return (subbytes2(bs,0));};
function bytes_eq_p(bs1,bs2){var n1=(bytes_length(bs1)),n2=(bytes_length(bs2)),is1=bs1[1],is2=bs2[1];return ((n1===n2)&&((function(b){{var i=0,t=n1,cont=true;while((true&&cont&&(i<t))){((function(i_27){skip:while(true){(b=(b&&(is1[i_27]===is2[i_27])));if(!((!b)===false)){(cont=false);break skip;}else ;;(i+=1);break skip;};;return undefined;})(i));};undefined;}return b;})(true)));};
function char_p(v){return ((array_p(v))&&((tag(v))===CHAR));};
function make_char(prim_js_str){return [CHAR,prim_js_str];};
function char__ginteger(c){var s=c[1];return (s.charCodeAt(0));};
function integer__gchar(i){return (String((String.fromCharCode(i))));};
function char_eq_p(c1,c2){return (c1[1]===c2[1]);};
function symbol_p(v){return ((array_p(v))&&((tag(v))===SYMBOL));};
function symbol_interned_p(sym){return ((typeof(sym[1]))==="string");};
function symbol_eq_p(sym1,sym2){return (((symbol_interned_p(sym1))&&(symbol_interned_p(sym2))&&(sym1[1]===sym2[1]))||(sym1===sym2));};
function symbol__gstring(sym){var js_str=sym[1],n=js_str.length,a=(Array((n+1)));(a[0]=MUTABLE_STRING);{var i=0,t=n;while((true&&true&&(i<t))){((function(i_28){(a[(i_28+1)]=js_str[i_28]);return (i+=1);})(i));};undefined;}return a;};
function symbol__gimmutable_string(sym){return (String(sym[1]));};
var symbol_table=[];
function string__gsymbol(str_29){var t=(typeof(str_29)),r,old;(old=symbol_table[str_29]);if(!((symbol_p(old))===false))((function(){return (r=old);})());else if(!((t==="string")===false))((function(){(r=[SYMBOL,str_29]);return (symbol_table[str_29]=r);})());else if(!((t==="object")===false))((function(){var n_a1=t.length,n=(n_a1-1),a=(Array(n));{var i=0,t_30=n;while((true&&true&&(i<t_30))){((function(i_31){(a[i_31]=str_29[(i_31+1)]);return (i+=1);})(i));};undefined;}(r=[SYMBOL,(String((a.join(""))))]);return (symbol_table[str_29]=r);})());else if(!(true===false))((function(){return (error("string->symbol","expected a string"));})());else undefined;;;;;return r;};
function string__guninterned_symbol(str_32){return [SYMBOL,new String(str_32)];};
var gensym_counter=0;
function gensym(base){return ((function(t){return (((false||(t===0))===false)?(((false||(t===1))===false)?((function(){return (error("gensym","expected at most one argument"));})()):((function(){return (gensym1(base));})())):((function(){return (gensym0());})()));})(arguments.length));};
function gensym0(){(gensym_counter+=1);return [SYMBOL,new String(("g"+gensym_counter))];};
function gensym1(base){(console.log(("gensym1: "+base)));(gensym_counter+=1);return [SYMBOL,new String((base+gensym_counter))];};
function symbol_l_p(a_sym,b_sym){return (string_l_p((symbol__gstring(a_sym)),(symbol__gstring(b_sym))));};
function error(who,msg){return (console.log(("error: "+who+": "+msg)));};
function keyword_p(v){return ((array_p(v))&&((tag(v))===KEYWORD));};
function keyword__gstring(key){return (immutable_string__gstring(key[1]));};
function string__gkeyword(str_33){var istr=(string__gimmutable_string(str_33));return [KEYWORD,istr];};
function keyword_l_p(key1,key2){return (key1[1]<key1[2]);};
function keyword_eq_p(key1,key2){return (key1[1]===key2[1]);};
function pair_p(v){return ((array_p(v))&&((tag(v))===PAIR));};
function null_p(v){return (v===NULL);};
function cons(a,d){return [PAIR,(list_p(d)),a,d];};
function unsafe_car(p){return p[2];};
var car=unsafe_car;
function unsafe_cdr(p){return p[3];};
var cdr=unsafe_cdr;
function cddr(v){return (cdr((cdr(v))));};
var Null=NULL;
function list_p(v){return ((v===NULL)||((array_p(v))&&((tag(v))===PAIR)&&v[1]));};
function list(){var args=arguments,n=args.length,n_1=(n-1),xs=NULL;{var i=0,t=n;while((true&&true&&(i<t))){((function(i_34){(xs=(cons(args[(n_1-i_34)],xs)));return (i+=1);})(i));};undefined;}return xs;};
function list_m(){var args=arguments,n=args.length;return (((n===0)===false)?((true===false)?undefined:((function(){var n_2=(n-2),xs=args[(n_2+1)];{var i=0,t=(n-1);while((true&&true&&(i<t))){((function(i_35){(xs=(cons(args[(n_2-i_35)],xs)));return (i+=1);})(i));};undefined;}return xs;})())):((function(){return (error("list*","expected one or more arguments"));})()));};
function build_list(n,proc){var a=(Array(n));{var i=0,t=n;while((true&&true&&(i<t))){((function(i_36){(a[i_36]=((proc[1])(proc,i_36)));return (i+=1);})(i));};undefined;}return (array__glist(a));};
function length(xs){var n=0;while((pair_p(xs))){(n+=1);(xs=(cdr(xs)));};return n;};
function list_ref(xs,i){var ret;if(!((i===0)===false))((function(){return (ret=(car(xs)));})());else if(!((i===1)===false))((function(){return (ret=(car((cdr(xs)))));})());else if(!(true===false))((function(){{var i_37=0,t=(i-1);while((true&&true&&(i_37<t))){((function(j){(xs=(cdr(xs)));return (i_37+=1);})(i_37));};undefined;}return (ret=(car(xs)));})());else undefined;;;;return ret;};
function list_tail(xs,pos){while((!(pos===0))){(xs=(cdr(xs)));(pos-=1);};return xs;};
function append(){var args=arguments,n=args.length;return ((function(t){return (((false||(t===0))===false)?(((false||(t===1))===false)?(((false||(t===2))===false)?((function(){var ret=args[(n-1)],i=(n-2);while((i>=0)){(ret=(append2(args[i],ret)));(i-=1);};return ret;})()):((function(){return (append2(args[0],args[1]));})())):((function(){return args[0];})())):((function(){return NULL;})()));})(n));};
function append2(xs,ys){var ret=ys;if(!((!(null_p(xs)))===false)){var axs=(list__garray(xs)),n=axs.length,n_1=(n-1);{var i=0,t=n;while((true&&true&&(i<t))){((function(i_38){(ret=(cons(axs[(n_1-i_38)],ret)));return (i+=1);})(i));};undefined;}}else ;;return ret;};
function reverse(xs){var result=NULL;while((!(null_p(xs)))){(result=(cons((car(xs)),result)));(xs=(cdr(xs)));};return result;};
function map(proc,xs,ys,zs){return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?(((false||(t===0))===false)?((function(){return (1/0);})()):((function(){return (error("map","expected at least two arguments"));})())):((function(){return ((function(xs_44){{var xs_45=xs,xs_46=ys,xs_47=zs;while((true&&true&&(!(null_p(xs_45)))&&(!(null_p(xs_46)))&&(!(null_p(xs_47))))){((function(x,y,z){(xs_44=(cons((proc.call(false,x,y,z)),xs_44)));(xs_45=(cdr(xs_45)));(xs_46=(cdr(xs_46)));return (xs_47=(cdr(xs_47)));})((car(xs_45)),(car(xs_46)),(car(xs_47))));};undefined;}return (reverse(xs_44));})(NULL));})())):((function(){return ((function(xs_41){{var xs_42=xs,xs_43=ys;while((true&&true&&(!(null_p(xs_42)))&&(!(null_p(xs_43))))){((function(x,y){(xs_41=(cons((proc.call(false,x,y)),xs_41)));(xs_42=(cdr(xs_42)));return (xs_43=(cdr(xs_43)));})((car(xs_42)),(car(xs_43))));};undefined;}return (reverse(xs_41));})(NULL));})())):((function(){return ((function(xs_39){{var xs_40=xs;while((true&&true&&(!(null_p(xs_40))))){((function(x){(xs_39=(cons((proc.call(false,x)),xs_39)));return (xs_40=(cdr(xs_40)));})((car(xs_40))));};undefined;}return (reverse(xs_39));})(NULL));})()));})(arguments.length));};
function andmap(proc,xs,ys,zs){return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?(((false||(t===0))===false)?((function(){return (1/0);})()):((function(){return (error("andmap","expected at least two arguments"));})())):((function(){return ((function(b){{var xs_51=xs,xs_52=ys,xs_53=zs,cont=true;while((true&&cont&&(!(null_p(xs_51)))&&(!(null_p(xs_52)))&&(!(null_p(xs_53))))){((function(x,y,z){skip:while(true){(b=(b&&(proc.call(false,x,y,z))));if(!((!b)===false)){(cont=false);break skip;}else ;;(xs_51=(cdr(xs_51)));(xs_52=(cdr(xs_52)));(xs_53=(cdr(xs_53)));break skip;};;return undefined;})((car(xs_51)),(car(xs_52)),(car(xs_53))));};undefined;}return b;})(true));})())):((function(){return ((function(b){{var xs_49=xs,xs_50=ys,cont=true;while((true&&cont&&(!(null_p(xs_49)))&&(!(null_p(xs_50))))){((function(x,y){skip:while(true){(b=(b&&(proc.call(false,x,y))));if(!((!b)===false)){(cont=false);break skip;}else ;;(xs_49=(cdr(xs_49)));(xs_50=(cdr(xs_50)));break skip;};;return undefined;})((car(xs_49)),(car(xs_50))));};undefined;}return b;})(true));})())):((function(){return ((function(b){{var xs_48=xs,cont=true;while((true&&cont&&(!(null_p(xs_48))))){((function(x){skip:while(true){(b=(b&&(proc.call(false,x))));if(!((!b)===false)){(cont=false);break skip;}else ;;(xs_48=(cdr(xs_48)));break skip;};;return undefined;})((car(xs_48))));};undefined;}return b;})(true));})()));})(arguments.length));};
function ormap(proc,xs,ys,zs){return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?(((false||(t===0))===false)?((function(){return (1/0);})()):((function(){return (error("ormap","expected at least two arguments"));})())):((function(){return ((function(b){{var xs_57=xs,xs_58=ys,xs_59=zs,cont=true;while((true&&cont&&(!(null_p(xs_57)))&&(!(null_p(xs_58)))&&(!(null_p(xs_59))))){((function(x,y,z){skip:while(true){(b=(b||(proc.call(false,x,y,z))));if(!(b===false)){(cont=false);break skip;}else ;;(xs_57=(cdr(xs_57)));(xs_58=(cdr(xs_58)));(xs_59=(cdr(xs_59)));break skip;};;return undefined;})((car(xs_57)),(car(xs_58)),(car(xs_59))));};undefined;}return b;})(false));})())):((function(){return ((function(b){{var xs_55=xs,xs_56=ys,cont=true;while((true&&cont&&(!(null_p(xs_55)))&&(!(null_p(xs_56))))){((function(x,y){skip:while(true){(b=(b||(proc.call(false,x,y))));if(!(b===false)){(cont=false);break skip;}else ;;(xs_55=(cdr(xs_55)));(xs_56=(cdr(xs_56)));break skip;};;return undefined;})((car(xs_55)),(car(xs_56))));};undefined;}return b;})(false));})())):((function(){return ((function(b){{var xs_54=xs,cont=true;while((true&&cont&&(!(null_p(xs_54))))){((function(x){skip:while(true){(b=(b||(proc.call(false,x))));if(!(b===false)){(cont=false);break skip;}else ;;(xs_54=(cdr(xs_54)));break skip;};;return undefined;})((car(xs_54))));};undefined;}return b;})(false));})()));})(arguments.length));};
function for_each(proc,xs,ys,zs){return ((function(t){return (((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?(((false||(t===0))===false)?((function(){return (1/0);})()):((function(){return (error("map","expected at least two arguments"));})())):((function(){return ((function(){var xs_63=xs,xs_64=ys,xs_65=zs;while((true&&true&&(!(null_p(xs_63)))&&(!(null_p(xs_64)))&&(!(null_p(xs_65))))){((function(x,y,z){(proc.call(false,x,y,z));(xs_63=(cdr(xs_63)));(xs_64=(cdr(xs_64)));return (xs_65=(cdr(xs_65)));})((car(xs_63)),(car(xs_64)),(car(xs_65))));};undefined;return undefined;})());})())):((function(){return ((function(){var xs_61=xs,xs_62=ys;while((true&&true&&(!(null_p(xs_61)))&&(!(null_p(xs_62))))){((function(x,y){(proc.call(false,x,y));(xs_61=(cdr(xs_61)));return (xs_62=(cdr(xs_62)));})((car(xs_61)),(car(xs_62))));};undefined;return undefined;})());})())):((function(){return ((function(){var xs_60=xs;while((true&&true&&(!(null_p(xs_60))))){((function(x){(proc.call(false,x));return (xs_60=(cdr(xs_60)));})((car(xs_60))));};undefined;return undefined;})());})()));})(arguments.length));};
function filter(pred,xs){var n=(length(xs)),a=(Array(n)),i=0;{var xs_66=xs;while((true&&true&&(!(null_p(xs_66))))){((function(x){var t=(pred.call(false,x));if(!(t===false)){(a[i]=x);(i+=1);}else ;;return (xs_66=(cdr(xs_66)));})((car(xs_66))));};undefined;}var xs_67=NULL;while((i>0)){(i-=1);(xs_67=(cons(a[i],xs_67)));};return xs_67;};
function list__garray(xs){var a,n=(length(xs));(a=(Array(n)));{var xs_68=xs,i=0;while((true&&true&&(!(null_p(xs_68))))){((function(x){(a[i]=x);(xs_68=(cdr(xs_68)));return (i+=1);})((car(xs_68))));};undefined;}return a;};
function array__glist(axs){var n=axs.length,n_1=(n-1),xs=NULL;{var i=0,t=n;while((true&&true&&(i<t))){((function(i_69){(xs=(cons(axs[(n_1-i_69)],xs)));return (i+=1);})(i));};undefined;}return xs;};
function array_end__glist(axs,from){var n=axs.length,n_1=(n-1),xs=NULL;{var i=0,t=(n_1-from);while((true&&true&&(i<t))){((function(i_70){(xs=(cons(axs[(n_1-i_70)],xs)));return (i+=1);})(i));};undefined;}return xs;};
var empty=NULL;
function cons_p(v){return (pair_p(v));};
function empty_p(v){return (null_p(v));};
function first(xs){return (car(xs));};
function rest(xs){return (cdr(xs));};
function second(xs){return (car((cdr(xs))));};
function third(xs){return (car((cdr((cdr(xs))))));};
function fourth(xs){return (car((cdr((cdr((cdr(xs))))))));};
function fifth(xs){return (car((cdr((cdr((cdr((cdr(xs))))))))));};
function sixth(xs){return (car((cdr((cdr((cdr((cdr((cdr(xs))))))))))));};
function seventh(xs){return (car((cdr((cdr((cdr((cdr((cdr((cdr(xs))))))))))))));};
function eighth(xs){return (car((cdr((cdr((cdr((cdr((cdr((cdr((cdr(xs))))))))))))))));};
function ninth(xs){return (car((cdr((cdr((cdr((cdr((cdr((cdr((cdr((cdr(xs))))))))))))))))));};
function tenth(xs){return (car((cdr((cdr((cdr((cdr((cdr((cdr((cdr((cdr((cdr(xs))))))))))))))))))));};
function last_pair(xs){while((!(null_p((cdr(xs)))))){(xs=(cdr(xs)));};return xs;};
function last(xs){return (car((last_pair(xs))));};
function make_list(k,v){return ((function(xs){{var i=0,t=k;while((true&&true&&(i<t))){((function(i_71){(xs=(cons(v,xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL));};
function vector_p(v){return ((array_p(v))&&(((tag(v))===VECTOR)||((tag(v))===IMMUTABLE_VECTOR)));};
function immutable_vector_p(v){return ((array_p(v))&&((tag(v))===IMMUTABLE_VECTOR));};
function mutable_vector_p(v){return ((array_p(v))&&((tag(v))===VECTOR));};
function make_vector(size,v){return ((function(t){return (((false||(t===1))===false)?(((false||(t===2))===false)?((function(){return (error("make-vector","expected one or two arguments"));})()):((function(){return (make_vector2(size,v));})())):((function(){return (make_vector2(size,0));})()));})(arguments.length));};
function make_vector2(size,v){var a=(Array((size+1)));(a[0]=VECTOR);{var i=1,t=(size+1);while((true&&true&&(i<t))){((function(i_72){(a[i_72]=v);return (i+=1);})(i));};undefined;}return a;};
function vector(){var args=arguments,n=args.length,a=(Array((n+1)));(a[0]=VECTOR);{var i=0,t=n;while((true&&true&&(i<t))){((function(j){(a[(j+1)]=args[j]);return (i+=1);})(i));};undefined;}return a;};
function vector_immutable(){var args=arguments,n=args.length,a=(Array((n+1)));(a[0]=IMMUTABLE_VECTOR);{var i=0,t=n;while((true&&true&&(i<t))){((function(j){(a[(j+1)]=args[j]);return (i+=1);})(i));};undefined;}return a;};
function vector_length(v){return (v.length-1);};
function vector_ref(v,i){return v[(i+1)];};
function vector_set_e(vec,i,v){return (vec[(i+1)]=v);};
function vector__glist(vec){var n=vec.length,xs=NULL;{var i=1,t=n;while((true&&true&&(i<t))){((function(i_73){(xs=(cons(vec[(n-i_73)],xs)));return (i+=1);})(i));};undefined;}return xs;};
function list__gvector(vs){var n=(length(vs)),vec=(Array((n+1))),i=1;(vec[0]=VECTOR);while((!(null_p(vs)))){(vec[i]=(car(vs)));(i+=1);(vs=(cdr(vs)));};return vec;};
function vector__gimmutable_vector(vec){var n=vec.length,a=(Array(n));(a[0]=IMMUTABLE_VECTOR);{var i=1,t=n;while((true&&true&&(i<t))){((function(j){(a[j]=vec[j]);return (i+=1);})(i));};undefined;}return vec;};
function vector_fill_e(vec,v){var n=vec.length;{var i=1,t=n;while((true&&true&&(i<t))){((function(i_74){(vec[i_74]=v);return (i+=1);})(i));};undefined;}return VOID;};
function vector_copy_e(dest,dest_start,src,src_start,src_end){return ((function(t){return (((false||(t===3))===false)?(((false||(t===4))===false)?(((false||(t===5))===false)?((function(){return (error("vector-copy!","expected 3, 4, or, 5 arguments"));})()):((function(){return (vector_copy_e5(dest,dest_start,src,src_start,src_end));})())):((function(){return (vector_copy_e5(dest,dest_start,src,src_start,(vector_length(src))));})())):((function(){return (vector_copy_e5(dest,dest_start,src,0,(vector_length(src))));})()));})(arguments.length));};
function vector_copy_e5(dest,dest_start,src,src_start,src_end){{var i=dest_start,i_75=src_start,t=src_end;while((true&&true&&true&&(i_75<t))){((function(i_76,j){(dest[i_76]=src[j]);(i+=1);return (i_75+=1);})(i,i_75));};undefined;}return VOID;};
function build_vector(n,proc){var a=(Array((n+1)));(a[0]=VECTOR);{var i=0,t=n;while((true&&true&&(i<t))){((function(i_77){(a[(i_77+1)]=(proc(i_77)));return (i+=1);})(i));};undefined;}return a;};
function box_p(v){return ((array_p(v))&&(((tag(v))===BOX)||((tag(v))===IMMUTABLE_BOX)));};
function box(v){return [BOX,v];};
function box_immutable(v){return [IMMUTABLE_BOX,v];};
function unbox(b){return b[1];};
function set_box_e(b,v){return (b[1]=v);};
function box_cas_e(b,old,new_78){return (((eq_p(b[1],old))===false)?false:((b[1]=new_78),true));};
function immutable_box_p(v){return ((array_p(v))&&((tag(v))===IMMUTABLE_BOX));};
function procedure_p(v){return ((typeof(v))==="function");};
function apply(proc,xs){var n=arguments.length;return ((function(t){return (((false||(t===0)||(t===1))===false)?(((false||(t===2))===false)?(((false||(t===3))===false)?(((false||(t===4))===false)?(((false||(t===5))===false)?(((false||(t===6))===false)?undefined:((function(){return (apply3(proc,((function(xs_79){{var i=1,t_80=(n-2);while((true&&true&&(i<t_80))){((function(i_81){(xs_79=(cons(arguments[i_81],xs_79)));return (i+=1);})(i));};undefined;}return (reverse(xs_79));})(NULL)),xs));})())):((function(){return (apply3(proc,(cons(arguments[1],(cons(arguments[2],(cons(arguments[3],NULL)))))),xs));})())):((function(){return (apply3(proc,(cons(arguments[1],(cons(arguments[2],NULL)))),xs));})())):((function(){return (apply3(proc,(cons(arguments[1],NULL)),xs));})())):((function(){return (apply3(proc,NULL,xs));})())):((function(){return (error("procedure?","expected two or more arguments"));})()));})(n));};
function apply3(proc,vs,xs){var nvs=(length(vs)),nxs=(length(xs)),n=(nvs+nxs),a=(Array(n));{var i=0,t=nvs,xs_82=vs;while((true&&true&&(i<t)&&(!(null_p(xs_82))))){((function(i_86,v){(a[i_86]=v);(i+=1);return (xs_82=(cdr(xs_82)));})(i,(car(xs_82))));};undefined;}{var i_85=nvs,t_84=n,xs_83=xs;while((true&&true&&(i_85<t_84)&&(!(null_p(xs_83))))){((function(i_87,x){(a[i_87]=x);(i_85+=1);return (xs_83=(cdr(xs_83)));})(i_85,(car(xs_83))));};undefined;}return (proc.apply(false,a));};
function void_p(v){return (v===VOID);};
function Void(){return VOID;};
function struct_type_descriptor_name(std){return std[1];};
function struct_type_descriptor_super(std){return std[2];};
function struct_type_descriptor_total_field_count(std){return std[3];};
function struct_type_descriptor_init_field_indices(std){return std[4];};
function struct_type_descriptor_auto_field_indices(std){return std[5];};
function struct_type_descriptor_auto_field_values(std){return std[6];};
function struct_type_descriptor_properties(std){return std[7];};
function struct_type_descriptor_inspector(std){return std[8];};
function struct_type_descriptor_immutables(std){return std[9];};
function struct_type_descriptor_guard(std){return std[10];};
function struct_type_descriptor_constructor_name(std){return std[11];};
function struct_type_descriptor_p(v){return ((array_p(v))&&(v[0]===STRUCT_TYPE_DESCRIPTOR));};
function struct_p(v){return ((array_p(v))&&(v[0]===STRUCT));};
function str_struct_type_descriptor(s){return ("(struct-type-descriptor "+(str(s[1]))+" "+(str(s[2]))+" "+(str(s[3]))+" "+(str(s[4]))+" "+(str(s[5]))+" "+(str(s[6]))+" "+(str(s[7]))+" "+(str(s[8]))+" "+(str(s[9]))+" "+(str(s[10]))+" "+(str(s[11]))+")");};
function str_struct(s){var n=s.length,fields=((function(a){{var i=2,t=n;while((true&&true&&(i<t))){((function(i_88){(a.push(s[i_88]));return (i+=1);})(i));};undefined;}return a;})([]));return ("(struct "+(str(s[1]))+" "+(fields.join(" "))+")");};
function make_struct_type_descriptor(name,super_type,init_field_count,auto_field_count,auto_field_value,props,inspector,proc_spec,immutables,guard,constructor_name){var ifc=init_field_count,afc=auto_field_count,stfc=((super_type===false)?0:(struct_type_descriptor_total_field_count(super_type)));return ((super_type===false)?((function(total_field_count,init_field_indices,auto_field_indices,auto_field_values){return [STRUCT_TYPE_DESCRIPTOR,name,false,total_field_count,init_field_indices,auto_field_indices,auto_field_values,NULL,false,NULL,false,false];})((ifc+afc),((function(xs){{var i=0,t=ifc;while((true&&true&&(i<t))){((function(i_92){(xs=(cons(i_92,xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL)),((function(xs){{var i=0,t=afc;while((true&&true&&(i<t))){((function(i_93){(xs=(cons((ifc+i_93),xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL)),((function(xs){{var i=0,t=afc;while((true&&true&&(i<t))){((function(i_94){(xs=(cons(auto_field_value,xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL)))):((function(total_field_count,new_init_field_indices,new_auto_field_indices,new_auto_field_values){return [STRUCT_TYPE_DESCRIPTOR,name,super_type,total_field_count,(append((struct_type_descriptor_init_field_indices(super_type)),new_init_field_indices)),(append((struct_type_descriptor_auto_field_indices(super_type)),new_auto_field_indices)),(append((struct_type_descriptor_auto_field_values(super_type)),new_auto_field_values)),NULL,false,NULL,false,false];})((ifc+afc+stfc),((function(xs){{var i=0,t=ifc;while((true&&true&&(i<t))){((function(i_89){(xs=(cons((stfc+i_89),xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL)),((function(xs){{var i=0,t=afc;while((true&&true&&(i<t))){((function(i_90){(xs=(cons((stfc+ifc+i_90),xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL)),((function(xs){{var i=0,t=afc;while((true&&true&&(i<t))){((function(i_91){(xs=(cons(auto_field_value,xs)));return (i+=1);})(i));};undefined;}return (reverse(xs));})(NULL)))));};
function make_struct_type(name,super_type,init_field_count,auto_field_count,auto_value,props,inspector,proc_spec,immutables,guard,constructor_name){return (do_make_struct_type(name,super_type,init_field_count,auto_field_count,(((auto_value===undefined)===false)?auto_value:false),(((props===undefined)===false)?props:NULL),(((inspector===undefined)===false)?inspector:false),(((proc_spec===undefined)===false)?proc_spec:false),(((immutables===undefined)===false)?immutables:NULL),(((guard===undefined)===false)?guard:false),(((constructor_name===undefined)===false)?constructor_name:false)));};
function do_make_struct_type(name,super_type,init_field_count,auto_field_count,auto_field_value,props,inspector,proc_spec,immutables,guard,constructor_name){var super_field_count=((super_type===false)?0:(struct_type_descriptor_total_field_count(super_type))),field_count=(init_field_count+auto_field_count+super_field_count),std=(make_struct_type_descriptor(name,super_type,init_field_count,auto_field_count,auto_field_value,props,inspector,proc_spec,immutables,guard,constructor_name));return ((super_type===false)?(values(std,(function(){var args=arguments,n=arguments.length,a=new Array((n+2));(a[0]=STRUCT);(a[1]=std);{var i=0,t=n;while((true&&true&&(i<t))){((function(i_100){(a[(i_100+2)]=args[i_100]);return (i+=1);})(i));};undefined;}{var i_99=n,t_98=(n+auto_field_count);while((true&&true&&(i_99<t_98))){((function(j){(a[(j+2)]=auto_field_value);return (i_99+=1);})(i_99));};undefined;}return a;}),(function(v){return (v===std);}),(function(s,index){return s[(index+2)];}),(function(s,index,value){(s[(index+2)]=value);return VOID;}))):(values(std,(function(){var args=arguments,n=arguments.length,a=new Array((field_count+2));(a[0]=STRUCT);(a[1]=std);{var xs=(struct_type_descriptor_init_field_indices(std)),i=0,t=n;while((true&&true&&(!(null_p(xs)))&&(i<t))){((function(i_97,j){(a[(i_97+2)]=args[j]);(xs=(cdr(xs)));return (i+=1);})((car(xs)),i));};undefined;}{var xs_95=(struct_type_descriptor_auto_field_indices(std)),xs_96=(struct_type_descriptor_auto_field_values(std));while((true&&true&&(!(null_p(xs_95)))&&(!(null_p(xs_96))))){((function(j,v){(a[(j+2)]=v);(xs_95=(cdr(xs_95)));return (xs_96=(cdr(xs_96)));})((car(xs_95)),(car(xs_96))));};undefined;}return a;}),(function(v){return (v===std);}),(function(s,index){return s[(super_field_count+index+2)];}),(function(s,index,value){(s[(super_field_count+index+2)]=value);return VOID;}))));};
function make_struct_field_accessor(accessor_proc,field_pos,field_name){return (function(s){return (accessor_proc(s,field_pos));});};
function values_p(v){return ((array_p(v))&&((tag(v))===VALUES));};
function values(){var args=arguments,n=args.length,a=(Array((n+1)));(a[0]=VALUES);{var i=0,t=n;while((true&&true&&(i<t))){((function(j){(a[(j+1)]=args[j]);return (i+=1);})(i));};undefined;}return a;};
function call_with_values(generator,receiver){var vals=(generator.call(false));return (((values_p(vals))===false)?((true===false)?undefined:((function(){return (receiver.apply(false,vals));})())):((function(){(vals.shift());return (receiver.apply(false,vals));})()));};
function displayln(v){return (console.log((str(v))));};
function newline(){return (console.log(""));};
function display(v){return ((process.stdout.write)((str(v))));};
function write(v){return ((process.stdout.write)((str(v))));};
function console_log(str_101){return (console.log(str_101));};
function current_inspector(){return false;};
function str_null(){return "()";};
function str_number(v){return (v.toString());};
function str_string(v){var s=(((mutable_string_p(v))===false)?v:(string__gimmutable_string(v)));return ("\""+s+"\"");};
function str_list(v){var a=((function(a){{var xs=v;while((true&&true&&(!(null_p(xs))))){((function(x){(a.push((str(x))));return (xs=(cdr(xs)));})((car(xs))));};undefined;}return a;})([]));return ("("+(a.join(" "))+")");};
function str_vector(v){var a=((function(a){{var xs=v,n=(vector_length(xs)),i=0;while((true&&true&&(i<n))){((function(x){(a.push((str(x))));return (i+=1);})(xs[(i+1)]));};undefined;}return a;})([]));return ("#("+(a.join(" "))+")");};
function str_pair(v){return ("("+(str((car(v))))+" . "+(str((cdr(v))))+")");};
function str_boolean(v){return (((v===true)===false)?(((v===false)===false)?((true===false)?undefined:((function(){return "str -internal error";})())):((function(){return "#f";})())):((function(){return "#t";})()));};
function str_symbol(v){return (string_append("'",(string__gimmutable_string((symbol__gstring(v))))));};
function str_keyword(v){return ("#:"+v[1]);};
function str_void(v){return "#<void>";};
function str_box(v){return ("#&"+(str((unbox(v)))));};
function str_box_immutable(v){return ("#&"+(str((unbox(v)))));};
function str_char(v){return ("#\\"+v[1]);};
function str_undefined(){return "#<js-undefined>";};
function str(v){return (((null_p(v))===false)?(((string_p(v))===false)?(((number_p(v))===false)?(((list_p(v))===false)?(((pair_p(v))===false)?(((vector_p(v))===false)?(((boolean_p(v))===false)?(((symbol_p(v))===false)?(((keyword_p(v))===false)?(((void_p(v))===false)?(((immutable_box_p(v))===false)?(((box_p(v))===false)?(((char_p(v))===false)?(((struct_type_descriptor_p(v))===false)?(((struct_p(v))===false)?(((v===undefined)===false)?((true===false)?undefined:((function(){(console.log(v));return "str - internal error";})())):((function(){return (str_undefined());})())):((function(){return (str_struct(v));})())):((function(){return (str_struct_type_descriptor(v));})())):((function(){return (str_char(v));})())):((function(){return (str_box(v));})())):((function(){return (str_box_immutable(v));})())):((function(){return (str_void(v));})())):((function(){return (str_keyword(v));})())):((function(){return (str_symbol(v));})())):((function(){return (str_boolean(v));})())):((function(){return (str_vector(v));})())):((function(){return (str_pair(v));})())):((function(){return (str_list(v));})())):((function(){return (str_number(v));})())):((function(){return (str_string(v));})())):((function(){return (str_null());})()));};
exports.gensym_counter=gensym_counter;
exports.symbol__gimmutable_string=symbol__gimmutable_string;
exports.string_g_eq_p=string_g_eq_p;
exports.string_l_eq_p=string_l_eq_p;
exports.string_g_p=string_g_p;
exports.string_l_p=string_l_p;
exports.make_char=make_char;
exports.string_eq_p=string_eq_p;
exports.string_set_e=string_set_e;
exports.string_ref=string_ref;
exports.string_length=string_length;
exports.string=string;
exports.subbytes3=subbytes3;
exports.subbytes2=subbytes2;
exports.immutable_bytes__gbytes=immutable_bytes__gbytes;
exports.display=display;
exports.make_bytes2=make_bytes2;
exports.make_bytes1=make_bytes1;
exports.bytes__gInt8Array=bytes__gInt8Array;
exports.string_append2=string_append2;
exports.substring2=substring2;
exports.substring3=substring3;
exports.immutable_string__gstring=immutable_string__gstring;
exports.make_primitive_string=make_primitive_string;
exports.make_string2=make_string2;
exports.make_string1=make_string1;
exports.newline=newline;
exports.image_part=image_part;
exports.list__gvector=list__gvector;
exports.make_struct_type=make_struct_type;
exports.gcd2=gcd2;
exports.ceiling=ceiling;
exports.$_q=$_q;
exports.$_m=$_m;
exports.$_=$_;
exports.$_a=$_a;
exports.immutable_box_p=immutable_box_p;
exports.immutable_bytes_p=immutable_bytes_p;
exports.keyword_eq_p=keyword_eq_p;
exports.immutable_string_p=immutable_string_p;
exports.VOID=VOID;
exports.STRUCT_TYPE_DESCRIPTOR=STRUCT_TYPE_DESCRIPTOR;
exports.VALUES=VALUES;
exports.KEYWORD=KEYWORD;
exports.SYMBOL=SYMBOL;
exports.MUTABLE_BYTES=MUTABLE_BYTES;
exports.BYTES=BYTES;
exports.MUTABLE_STRING=MUTABLE_STRING;
exports.CHAR=CHAR;
exports.IMMUTABLE_BOX=IMMUTABLE_BOX;
exports.BOX=BOX;
exports.IMMUTABLE_VECTOR=IMMUTABLE_VECTOR;
exports.VECTOR=VECTOR;
exports.PAIR=PAIR;
exports.fourth=fourth;
exports.fifth=fifth;
exports.seventh=seventh;
exports.eighth=eighth;
exports.sixth=sixth;
exports.symbol_eq_p=symbol_eq_p;
exports.last_pair=last_pair;
exports.ninth=ninth;
exports.empty_p=empty_p;
exports.empty=empty;
exports.make_list=make_list;
exports.rest=rest;
exports.cons_p=cons_p;
exports.list__garray=list__garray;
exports.last=last;
exports.vector__gimmutable_vector=vector__gimmutable_vector;
exports.vector_copy_e=vector_copy_e;
exports.mutable_bytes_p=mutable_bytes_p;
exports.mutable_string_p=mutable_string_p;
exports.sub1=sub1;
exports.vector_ref=vector_ref;
exports.vector_length=vector_length;
exports.vector_immutable=vector_immutable;
exports.exact__ginexact=exact__ginexact;
exports.vector=vector;
exports.angle=angle;
exports.displayln=displayln;
exports.array_end__glist=array_end__glist;
exports.array__glist=array__glist;
exports.str=str;
exports.NULL=NULL;
exports.truncate=truncate;
exports.unsafe_cdr=unsafe_cdr;
exports.unsafe_car=unsafe_car;
exports.filter=filter;
exports.first=first;
exports.tenth=tenth;
exports.immutable_vector_p=immutable_vector_p;
exports.mutable_vector_p=mutable_vector_p;
exports.tag=tag;
exports.console_log=console_log;
exports.current_pseudo_random_generator=current_pseudo_random_generator;
exports.pseudo_random_generator_p=pseudo_random_generator_p;
exports.pseudo_random_generator_vector_p=pseudo_random_generator_vector_p;
exports.pseudo_random_generator__gvector=pseudo_random_generator__gvector;
exports.vector__gpseudo_random_generator_e=vector__gpseudo_random_generator_e;
exports.vector__gpseudo_random_generator=vector__gpseudo_random_generator;
exports.make_pseudo_random_generator=make_pseudo_random_generator;
exports.random_seed=random_seed;
exports.random=random;
exports.apply=apply;
exports.Void=Void;
exports.string__gnumber=string__gnumber;
exports.number__gstring=number__gstring;
exports.min=min;
exports.max=max;
exports.negative_p=negative_p;
exports.positive_p=positive_p;
exports.zero_p=zero_p;
exports.current_inspector=current_inspector;
exports.modulo=modulo;
exports.quotient_qremainder=quotient_qremainder;
exports.remainder=remainder;
exports.quotient=quotient;
exports.abs=abs;
exports.STRUCT=STRUCT;
exports.add1=add1;
exports.inexact__gexact=inexact__gexact;
exports.pi=pi;
exports.magnitude=magnitude;
exports.nan_p=nan_p;
exports.infinite_p=infinite_p;
exports.real_part=real_part;
exports.struct_p=struct_p;
exports.expt=expt;
exports.integer_sqrt_qremainder=integer_sqrt_qremainder;
exports.integer_sqrt=integer_sqrt;
exports.sqrt=sqrt;
exports.atan=atan;
exports.acos=acos;
exports.asin=asin;
exports.tan=tan;
exports.cos=cos;
exports.sin=sin;
exports.log=log;
exports.exp=exp;
exports.round=round;
exports.make_string=make_string;
exports.string_p=string_p;
exports.floor=floor;
exports.gcd=gcd;
exports.write=write;
exports.even_p=even_p;
exports.odd_p=odd_p;
exports.inexact_p=inexact_p;
exports.exact_p=exact_p;
exports.real__gdouble_flonum=real__gdouble_flonum;
exports.real__gsingle_flonum=real__gsingle_flonum;
exports.single_flonum_p=single_flonum_p;
exports.flonum_p=flonum_p;
exports.inexact_real_p=inexact_real_p;
exports.fixnum_p=fixnum_p;
exports.exact_positive_integer_p=exact_positive_integer_p;
exports.exact_nonnegative_integer_p=exact_nonnegative_integer_p;
exports.exact_integer_p=exact_integer_p;
exports.integer_p=integer_p;
exports.rational_p=rational_p;
exports.real_p=real_p;
exports.complex_p=complex_p;
exports.number_p=number_p;
exports.Null=Null;
exports.error=error;
exports.array_p=array_p;
exports.vector_set_e=vector_set_e;
exports.values_p=values_p;
exports.build_list=build_list;
exports.make_vector=make_vector;
exports.build_vector=build_vector;
exports.box_cas_e=box_cas_e;
exports.set_box_e=set_box_e;
exports.unbox=unbox;
exports.box_p=box_p;
exports.box_immutable=box_immutable;
exports.box=box;
exports.double_flonum_p=double_flonum_p;
exports.equal_p=equal_p;
exports.eqv_p=eqv_p;
exports.eq_p=eq_p;
exports.boolean_p=boolean_p;
exports.second=second;
exports.third=third;
exports.ormap=ormap;
exports.str_struct_type_descriptor=str_struct_type_descriptor;
exports.integer__gchar=integer__gchar;
exports.char__ginteger=char__ginteger;
exports.cddr=cddr;
exports.list_ref=list_ref;
exports.list_tail=list_tail;
exports.append=append;
exports.length=length;
exports.immutable_p=immutable_p;
exports.list_m=list_m;
exports.list=list;
exports.list_p=list_p;
exports.null_p=null_p;
exports.make_struct_field_accessor=make_struct_field_accessor;
exports.char_eq_p=char_eq_p;
exports.char_p=char_p;
exports.do_make_struct_type=do_make_struct_type;
exports.cdr=cdr;
exports.car=car;
exports.cons=cons;
exports.vector_fill_e=vector_fill_e;
exports.pair_p=pair_p;
exports.vector__glist=vector__glist;
exports.gensym=gensym;
exports.keyword__gstring=keyword__gstring;
exports.string__gkeyword=string__gkeyword;
exports.keyword_l_p=keyword_l_p;
exports.keyword_p=keyword_p;
exports.symbol__gstring=symbol__gstring;
exports.vector_p=vector_p;
exports.string__guninterned_symbol=string__guninterned_symbol;
exports.string__gsymbol=string__gsymbol;
exports.symbol_l_p=symbol_l_p;
exports.symbol_interned_p=symbol_interned_p;
exports.symbol_p=symbol_p;
exports.struct_type_descriptor_properties=struct_type_descriptor_properties;
exports.reverse=reverse;
exports.struct_type_descriptor_auto_field_values=struct_type_descriptor_auto_field_values;
exports.struct_type_descriptor_auto_field_indices=struct_type_descriptor_auto_field_indices;
exports.str_struct=str_struct;
exports.void_p=void_p;
exports.struct_type_descriptor_p=struct_type_descriptor_p;
exports.struct_type_descriptor_constructor_name=struct_type_descriptor_constructor_name;
exports.struct_type_descriptor_inspector=struct_type_descriptor_inspector;
exports.bytes__gimmutable_bytes=bytes__gimmutable_bytes;
exports.bytes_copy=bytes_copy;
exports.map=map;
exports.for_each=for_each;
exports.andmap=andmap;
exports.subbytes=subbytes;
exports.make_struct_type_descriptor=make_struct_type_descriptor;
exports.bytes_eq_p=bytes_eq_p;
exports.bytes_set_e=bytes_set_e;
exports.bytes_ref=bytes_ref;
exports.bytes_length=bytes_length;
exports.struct_type_descriptor_guard=struct_type_descriptor_guard;
exports.struct_type_descriptor_immutables=struct_type_descriptor_immutables;
exports.bytes=bytes;
exports.make_bytes=make_bytes;
exports.bytes_p=bytes_p;
exports.byte_p=byte_p;
exports.struct_type_descriptor_init_field_indices=struct_type_descriptor_init_field_indices;
exports.struct_type_descriptor_total_field_count=struct_type_descriptor_total_field_count;
exports.struct_type_descriptor_super=struct_type_descriptor_super;
exports.struct_type_descriptor_name=struct_type_descriptor_name;
exports.apply3=apply3;
exports.string_upcase=string_upcase;
exports.values=values;
exports.append2=append2;
exports.string__gimmutable_string=string__gimmutable_string;
exports.call_with_values=call_with_values;
exports.procedure_p=procedure_p;
exports.string__glist=string__glist;
exports.string_append=string_append;
exports.substring=substring;
